In [1]:
import os
import pandas as pd
from dotenv import load_dotenv
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

In [2]:
# 1. Carregar credenciais
load_dotenv()
client = bigquery.Client()

In [3]:
# 1. O ID do Projeto (A Nuvem)
# DEVE ser o ID real que está no seu console do Google Cloud (ou pego via client.project)
PROJECT_ID = client.project
# 2. O seu "Banco de Dados" (Dataset)
# Aqui sim entra o nome que você escolheu!
DB_NAME = "analytics_ford"
# 3. A sua Tabela
TABLE_NAME = "marcas_veiculos"

# Formato: projeto.dataset
DATASET_ID = f"{PROJECT_ID}.{DB_NAME}" 

# Formato: projeto.dataset.tabela
TABLE_ID = f"{DATASET_ID}.{TABLE_NAME}" 

print(f"O caminho final da tabela será: {TABLE_ID}")
# Resultado esperado: id-do-seu-projeto-gcp.analytics_ford.marcas_veiculos

O caminho final da tabela será: ford-493401.analytics_ford.marcas_veiculos

In [ ]:
def preparar_infraestrutura():
    """Cria o dataset e a tabela caso não existam."""
    
    # Criar Dataset se não existir
    try:
        client.get_dataset(DATASET_ID)
        print(f"Dataset {DATASET_ID} já existe.")
    except NotFound:
        dataset = bigquery.Dataset(DATASET_ID)
        dataset.location = "US"  # Escolha a região
        client.create_dataset(dataset)
        print(f"Dataset {DATASET_ID} criado.")

    # Definir o Schema (Estrutura da Tabela)
    schema = [
        bigquery.SchemaField("tipo_veiculo", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("marca_nome", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("marca_codigo", "STRING", mode="REQUIRED"),
    ]

    # Criar Tabela se não existir
    try:
        client.get_table(TABLE_ID)
        print(f"Tabela {TABLE_ID} já existe.")
    except NotFound:
        table = bigquery.Table(TABLE_ID, schema=schema)
        client.create_table(table)
        print(f"Tabela {TABLE_ID} criada.")

def salvar_no_bigquery(df):
    """Ingere o DataFrame do Pandas na tabela do BigQuery."""
    print(f"Iniciando ingestão de {len(df)} linhas no BigQuery...")
    
    # Configuração da carga: sobrescrever dados antigos (WRITE_TRUNCATE) 
    # ou apenas adicionar (WRITE_APPEND)
    job_config = bigquery.LoadJobConfig(
        write_disposition="WRITE_TRUNCATE", 
    )

    job = client.load_table_from_dataframe(df, TABLE_ID, job_config=job_config)
    job.result()  # Aguarda a conclusão
    
    print(f"Dados salvos com sucesso na tabela {TABLE_ID}!")

# --- EXECUÇÃO ---
if __name__ == "__main__":
    # 1. Garantir que o banco e a tabela existem
    preparar_infraestrutura()
    
    # 2. Chamar sua função de extração (que você postou acima)
    # Supondo que a função extrair_mapeamento_marcas() esteja no mesmo arquivo
    # df_resultado = extrair_mapeamento_marcas()
    
    # 3. Salvar o resultado
    # salvar_no_bigquery(df_resultado)

Dataset ford-493401.analytics_ford já existe.
Tabela ford-493401.analytics_ford.marcas_veiculos criada.

:

In [18]:
query = f"""
    SELECT 
        tipo_veiculo, 
        marca_nome, 
        marca_codigo
    FROM 
        `{PROJECT_ID}.analytics_ford.marcas_veiculos`
    WHERE tipo_veiculo IN ('carros')
    ORDER BY 
        tipo_veiculo, marca_nome

"""
    
# 3. Executar a consulta (Job)
# query_job = client.query(query)
    
  
df_resultado = client.query(query).to_dataframe()
    


df_resultado

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

    tipo_veiculo    marca_nome marca_codigo
0         carros        AM Gen            4
1         carros  ASTON MARTIN          189
2         carros         Acura            1
3         carros        Agrale            2
4         carros    Alfa Romeo            3
..           ...           ...          ...
101       carros         Volvo           58
102       carros          Wake          163
103       carros          Walk          120
104       carros         ZEEKR          253
105       carros         smart          157

[106 rows x 3 columns]

In [20]:
df_resultado

    tipo_veiculo    marca_nome marca_codigo
0         carros        AM Gen            4
1         carros  ASTON MARTIN          189
2         carros         Acura            1
3         carros        Agrale            2
4         carros    Alfa Romeo            3
..           ...           ...          ...
101       carros         Volvo           58
102       carros          Wake          163
103       carros          Walk          120
104       carros         ZEEKR          253
105       carros         smart          157

[106 rows x 3 columns]

In [29]:
df_resultado['marca_codigo'] = df_resultado['marca_codigo'].astype(str).str.lower()

In [32]:
df_resultado['marca_nome'] = df_resultado['marca_nome'].astype(str).str.lower()

In [36]:
codigo_ford = df_resultado[df_resultado['marca_nome'] == 'ford']['marca_codigo'].iloc[0]

In [37]:
codigo_ford

'22'

In [38]:
import os
import time
import requests
import pandas as pd
from dotenv import load_dotenv
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

# ==========================================
# 1. CONFIGURAÇÃO E CREDENCIAIS
# ==========================================
load_dotenv()
client = bigquery.Client()
project_id = client.project

DB_NAME = "analytics_ford"
TABELA_ORIGEM = f"{project_id}.{DB_NAME}.marcas_veiculos"
TABELA_DESTINO = f"{project_id}.{DB_NAME}.modelos_veiculos"

# ==========================================
# 2. FUNÇÕES DE INFRAESTRUTURA E API
# ==========================================
def preparar_tabela_modelos():
    """Cria a tabela de destino para os modelos, se não existir."""
    schema = [
        bigquery.SchemaField("tipo_veiculo", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("marca_codigo", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("modelo_codigo", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("modelo_nome", "STRING", mode="REQUIRED"),
    ]
    try:
        client.get_table(TABELA_DESTINO)
    except NotFound:
        table = bigquery.Table(TABELA_DESTINO, schema=schema)
        client.create_table(table)
        print(f"✨ Tabela {TABELA_DESTINO} criada.")

def extrair_modelos_por_marca(cod_marca, tipo_veiculo):
    """Consulta a API da Fipe para extrair modelos de uma marca específica."""
    base_url = "https://parallelum.com.br/fipe/api/v1"
    headers = {'User-Agent': 'Mozilla/5.0'}
    url = f"{base_url}/{tipo_veiculo}/marcas/{cod_marca}/modelos"
    
    print(f"Buscando na API: {tipo_veiculo.upper()} | ID: {cod_marca}...")

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        
        lista_modelos = response.json().get('modelos', [])
        if not lista_modelos: return pd.DataFrame()

        df_modelos = pd.DataFrame(lista_modelos)
        df_modelos = df_modelos.rename(columns={'codigo': 'modelo_codigo', 'nome': 'modelo_nome'})
        
        df_modelos['marca_codigo'] = str(cod_marca)
        df_modelos['tipo_veiculo'] = str(tipo_veiculo)
        df_modelos['modelo_codigo'] = df_modelos['modelo_codigo'].astype(str)
        df_modelos['modelo_nome'] = df_modelos['modelo_nome'].astype(str)

        return df_modelos[['tipo_veiculo', 'marca_codigo', 'modelo_codigo', 'modelo_nome']]

    except Exception as e:
        print(f"❌ Erro na API para a marca {cod_marca}: {e}")
        return pd.DataFrame()

# ==========================================
# 3. NOVO PIPELINE SOB DEMANDA
# ==========================================
def executar_pipeline_por_marca(nome_marca_alvo):
    print("--- 1. Preparando Infraestrutura ---")
    preparar_tabela_modelos()
    
    print(f"\n--- 2. Buscando código da marca: '{nome_marca_alvo}' no BigQuery ---")
    # Usamos LOWER para ignorar se você digitou 'Ford', 'FORD' ou 'ford'
    query = f"""
        SELECT tipo_veiculo, marca_codigo, marca_nome 
        FROM `{TABELA_ORIGEM}`
        WHERE LOWER(marca_nome) = LOWER('{nome_marca_alvo}')
    """
    
    df_marcas = client.query(query).to_dataframe()
    
    if df_marcas.empty:
        print(f"❌ A marca '{nome_marca_alvo}' não foi encontrada na tabela {TABELA_ORIGEM}.")
        return

    print(f"✅ Encontrada(s) {len(df_marcas)} correspondência(s) para '{nome_marca_alvo}':")
    for _, row in df_marcas.iterrows():
        print(f"   -> Categoria: {row['tipo_veiculo']} | Código: {row['marca_codigo']}")

    print("\n--- 3. Extraindo Modelos da API ---")
    lista_dfs = []
    
    for index, row in df_marcas.iterrows():
        df_resultado = extrair_modelos_por_marca(row['marca_codigo'], row['tipo_veiculo'])
        if not df_resultado.empty:
            lista_dfs.append(df_resultado)
        time.sleep(0.5) 
        
    print("\n--- 4. Salvando no BigQuery ---")
    if lista_dfs:
        df_final = pd.concat(lista_dfs, ignore_index=True)
        print(f"Total de modelos extraídos: {len(df_final)}. Iniciando upload...")
        
        # MUDANÇA IMPORTANTE: WRITE_APPEND adiciona sem apagar o resto!
        job_config = bigquery.LoadJobConfig(write_disposition="WRITE_APPEND")
        job = client.load_table_from_dataframe(df_final, TABELA_DESTINO, job_config=job_config)
        job.result()
        
        print(f"🎉 Sucesso! Modelos da '{nome_marca_alvo}' adicionados à tabela {TABELA_DESTINO}.")
    else:
        print("Nenhum modelo foi extraído.")

# ==========================================
# EXECUÇÃO
# ==========================================
if __name__ == "__main__":
    # Teste digitando o nome da marca que você quer extrair!
    # Pode ser "Ford", "Fiat", "Honda", "Yamaha"...
    marca_desejada = input("Digite o nome da marca que deseja extrair: ")
    
    executar_pipeline_por_marca(marca_desejada)

--- 1. Preparando Infraestrutura ---
✨ Tabela ford-493401.analytics_ford.modelos_veiculos criada.

--- 2. Buscando código da marca: 'ford' no BigQuery ---

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

✅ Encontrada(s) 2 correspondência(s) para 'ford':
   -> Categoria: caminhoes | Código: 105
   -> Categoria: carros | Código: 22

--- 3. Extraindo Modelos da API ---
Buscando na API: CAMINHOES | ID: 105...
Buscando na API: CARROS | ID: 22...

--- 4. Salvando no BigQuery ---
Total de modelos extraídos: 651. Iniciando upload...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

🎉 Sucesso! Modelos da 'ford' adicionados à tabela ford-493401.analytics_ford.modelos_veiculos.

In [ ]:
query = f"""
    SELECT 
      *
    FROM 
        `{PROJECT_ID}.analytics_ford.modelos_veiculos`


"""
    
# 3. Executar a consulta (Job)
# query_job = client.query(query)
    
  
df_resultado = client.query(query).to_dataframe()
    


df_resultado

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,tipo_veiculo,marca_codigo,modelo_codigo,modelo_nome
0,caminhoes,105,3151,CARGO 1113 2p (diesel)
1,caminhoes,105,3152,CARGO 1113 3-Eixos 2p (diesel)
2,caminhoes,105,3153,CARGO 1114 2p (diesel)
3,caminhoes,105,3154,CARGO 1114 3-Eixos 2p (diesel)
4,caminhoes,105,3155,CARGO 1117 T 3-Eixos 2p (diesel)
...,...,...,...,...
646,carros,22,921,Versailles Ghia 2.0i / 2.0 2p e 4p
647,carros,22,922,Versailles GL 1.8i / 1.8 2p e 4p
648,carros,22,923,Versailles GL 2.0i / 2.0 2p e 4p
649,carros,22,924,Windstar GL
650,carros,22,925,Windstar LX

In [42]:
df_resultado_carros = df_resultado[df_resultado['tipo_veiculo'] == 'carros']

In [45]:
df_resultado_carros.query("modelo_nome.str.lower().str.contains('territory')")

,tipo_veiculo,marca_codigo,modelo_codigo,modelo_nome
614,carros,22,9163,TERRITORY SEL 1.5 GTDi EcoBoost Aut.
615,carros,22,9164,TERRITORY Titanium 1.5 GTDi EcoBo. Aut.

In [46]:
tipo_veiculo = 'carros'
cod_marca = '22'  # Exemplo: código da marca Ford para carros
base_url = "https://parallelum.com.br/fipe/api/v1"
headers = {'User-Agent': 'Mozilla/5.0'}
url = f"{base_url}/{tipo_veiculo}/marcas/{cod_marca}/modelos"

In [48]:
url_anos = f"{base_url}/{tipo_veiculo}/marcas/{cod_marca}/modelos/{9164}/anos"

In [49]:
url_anos

'https://parallelum.com.br/fipe/api/v1/carros/marcas/22/modelos/9164/anos'

In [47]:
url

'https://parallelum.com.br/fipe/api/v1/carros/marcas/22/modelos'

In [51]:
import os
import time
import requests
import pandas as pd
from dotenv import load_dotenv
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

# ==========================================
# 1. CONFIGURAÇÃO
# ==========================================
load_dotenv()
client = bigquery.Client()
project_id = client.project or os.getenv("GOOGLE_CLOUD_PROJECT")

# Usando exatamente as tabelas que você definiu
DB_NAME = "analytics_ford"
TABELA_ORIGEM = f"{project_id}.{DB_NAME}.modelos_veiculos"
TABELA_DESTINO = f"{project_id}.{DB_NAME}.modelos_com_fipe"

TAMANHO_DO_LOTE = 50  # Salva no BigQuery a cada 50 modelos encontrados

# ==========================================
# 2. FUNÇÕES BASE
# ==========================================
def preparar_tabela_destino():
    """Garante que a tabela final exista antes de começar."""
    schema = [
        bigquery.SchemaField("tipo_veiculo", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("marca_codigo", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("modelo_codigo", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("modelo_nome", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("codigo_fipe", "STRING", mode="REQUIRED"),
    ]
    try:
        client.get_table(TABELA_DESTINO)
    except NotFound:
        table = bigquery.Table(TABELA_DESTINO, schema=schema)
        client.create_table(table)
        print(f"✨ Tabela de destino {TABELA_DESTINO} criada.")

def buscar_fipe_na_api(cod_marca, cod_modelo, tipo_veiculo):
    """Bate na API da Fipe e retorna o código oficial usando Token de Autenticação."""
    base_url = "https://parallelum.com.br/fipe/api/v1"
    
    # 1. Puxa o token do arquivo .env
    token_fipe = os.getenv("FIPE_API_TOKEN")
    
    # 2. Adiciona o token no cabeçalho da requisição
    headers = {
        'User-Agent': 'Mozilla/5.0',
        'X-Subscription-Token': token_fipe
    }
    
    url_anos = f"{base_url}/{tipo_veiculo}/marcas/{cod_marca}/modelos/{cod_modelo}/anos"

    try:
        resp_anos = requests.get(url_anos, headers=headers)
        resp_anos.raise_for_status()
        anos = resp_anos.json()

        if not anos: return None

        primeiro_ano = anos[0]['codigo']
        url_final = f"{base_url}/{tipo_veiculo}/marcas/{cod_marca}/modelos/{cod_modelo}/anos/{primeiro_ano}"
        
        # A segunda requisição também usa o mesmo 'headers' com o token
        resp_final = requests.get(url_final, headers=headers)
        resp_final.raise_for_status()

        return resp_final.json().get('CodigoFipe')

    except Exception as e:
        # Opcional: imprimir o erro para debug caso o token seja recusado (Erro 401 ou 403)
        print(f"Erro na API: {e}")
        return None

# ==========================================
# 3. MOTOR PRINCIPAL (PROCESSAMENTO EM LOTES)
# ==========================================
def rodar_extracao_massiva():
    preparar_tabela_destino()
    
    print("\n🔍 Analisando o banco de dados para descobrir o que falta...")
    
    # Esta query é mágica: Ela pega todos os modelos, cruza com a tabela de destino
    # e só retorna quem AINDA NÃO TEM Fipe salvo.
    query = f"""
        SELECT 
            o.tipo_veiculo, o.marca_codigo, o.modelo_codigo, o.modelo_nome
        FROM 
            `{TABELA_ORIGEM}` o
        LEFT JOIN 
            `{TABELA_DESTINO}` d
          ON o.modelo_codigo = d.modelo_codigo AND o.marca_codigo = d.marca_codigo
        WHERE 
            d.codigo_fipe IS NULL
    """
    
    df_pendentes = client.query(query).to_dataframe()
    total = len(df_pendentes)
    
    if total == 0:
        print("✅ Parabéns! Todos os modelos do banco já possuem código FIPE.")
        return

    print(f"🚀 Iniciando extração de {total} modelos pendentes. Lotes de {TAMANHO_DO_LOTE}.")
    print("-" * 50)

    lote_atual = []
    
    # Iterar sobre as linhas pendentes
    for index, row in df_pendentes.iterrows():
        cod_marca = row['marca_codigo']
        cod_modelo = row['modelo_codigo']
        tipo = row['tipo_veiculo']
        nome = row['modelo_nome']
        
        print(f"[{index + 1}/{total}] Buscando: {nome[:25].ljust(25)}...", end=" ")
        
        fipe = buscar_fipe_na_api(cod_marca, cod_modelo, tipo)
        
        if fipe:
            print(f"OK ({fipe})")
            # Adiciona ao lote em formato de dicionário
            lote_atual.append({
                "tipo_veiculo": tipo,
                "marca_codigo": cod_marca,
                "modelo_codigo": cod_modelo,
                "modelo_nome": nome,
                "codigo_fipe": fipe
            })
        else:
            print("FALHOU")
            
        # Pausa obrigatória para a API não bloquear seu IP
        time.sleep(0.5)
        
        # --- LÓGICA DE SALVAMENTO EM LOTE ---
        if len(lote_atual) >= TAMANHO_DO_LOTE:
            print(f"\n💾 Salvando lote de {len(lote_atual)} registros no BigQuery...")
            df_lote = pd.DataFrame(lote_atual)
            
            job_config = bigquery.LoadJobConfig(write_disposition="WRITE_APPEND")
            job = client.load_table_from_dataframe(df_lote, TABELA_DESTINO, job_config=job_config)
            job.result()
            
            print("✔️ Lote salvo com sucesso!\n")
            lote_atual = [] # Limpa o lote para começar o próximo

    # --- SALVAR O RESTO (Se sobrou algo no último lote) ---
    if len(lote_atual) > 0:
        print(f"\n💾 Salvando lote final de {len(lote_atual)} registros no BigQuery...")
        df_lote = pd.DataFrame(lote_atual)
        job_config = bigquery.LoadJobConfig(write_disposition="WRITE_APPEND")
        client.load_table_from_dataframe(df_lote, TABELA_DESTINO, job_config=job_config).result()
        print("✔️ Último lote salvo com sucesso!")

if __name__ == "__main__":
    rodar_extracao_massiva()

🔍 Analisando o banco de dados para descobrir o que falta...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

🚀 Iniciando extração de 410 modelos pendentes. Lotes de 50.
--------------------------------------------------
[1/410] Buscando: Escort RS 1.8i 16V       ... OK (003095-3)
[2/410] Buscando: Escort S.W GL 1.8i 16V   ... OK (003006-6)
[3/410] Buscando: Escort S.W. GLX 1.8i 16V ... OK (003008-2)
[4/410] Buscando: Escort SW 1.9 16v        ... OK (003230-1)
[5/410] Buscando: Escort SW GL 1.6 MPI     ... OK (003208-5)
[6/410] Buscando: Escort XR3 1.8 / 1.6 Bene... OK (003038-4)
[7/410] Buscando: Escort XR3 1.8 / 1.6 Conv... OK (003039-2)
[8/410] Buscando: Escort XR3 2.0i          ... OK (003040-6)
[9/410] Buscando: Escort XR3 2.0i Conversív... OK (003041-4)
[10/410] Buscando: E-TRANSIT Furgão Longo Te... OK (003514-9)
[11/410] Buscando: Expedition 5.4 V8        ... OK (003154-2)
[12/410] Buscando: Explorer Limited 4.0 4x4 ... OK (003290-5)
[13/410] Buscando: Explorer Limited 5.0 4x4 ... OK (003138-0)
[14/410] Buscando: Explorer Sport 4.0 V6    ... OK (003157-7)
[15/410] Buscando: Explorer XL 4x2 4.0 V6   ... OK (003155-0)
[16/410] Buscando: Explorer XL 4x4 4.0 V6   ... OK (003156-9)
[17/410] Buscando: Explorer XLT 4x2 4.0 V6  ... OK (003073-2)
[18/410] Buscando: Explorer XLT 4x4 4.0 V6  ... OK (003074-0)
[19/410] Buscando: F-100 2.3                ... OK (003185-2)
[20/410] Buscando: F-100 Blazer 2.3         ... OK (003186-0)
[21/410] Buscando: F-100 CD 2.3             ... OK (003187-9)
[22/410] Buscando: F-100 Super 2.3          ... OK (003188-7)
[23/410] Buscando: F-100 Super Série 2.3    ... OK (003189-5)
[24/410] Buscando: F-1000 CD/Blazer 3.6     ... OK (003162-3)
[25/410] Buscando: F-1000 CD/Blazer 3.9 Dies... OK (003163-1)
[26/410] Buscando: F-1000 Lightning/ Super 4... OK (003164-0)
[27/410] Buscando: F-1000 Regular Cab. 4.9i ... OK (003009-0)
[28/410] Buscando: F-1000 S. S. Diesel / S.S... OK (003048-1)
[29/410] Buscando: F-1000 SR XK  Deserter Di... OK (003124-0)
[30/410] Buscando: F-1000 SR XK Deserter    ... OK (003222-0)
[31/410] Buscando: F-1000 Super 3.6 / Super ... OK (003042-2)
[32/410] Buscando: F-1000 Super CE 4.9i / 3.... OK (003043-0)
[33/410] Buscando: F-1000 Super Diesel / Sup... OK (003046-5)
[34/410] Buscando: F-1000 Super Diesel CE 3.... OK (003045-7)
[35/410] Buscando: F-1000 Super Série CE 4.9... OK (003044-9)
[36/410] Buscando: F-1000 Super Série CE Die... OK (003047-3)
[37/410] Buscando: F-1000 Super/ S.Série 4x4... OK (003049-0)
[38/410] Buscando: F-1000 Tropical CD 4.9i  ... OK (003166-6)
[39/410] Buscando: F-1000 Tropical CD HSD 2.... OK (003165-8)
[40/410] Buscando: F-1000 Tropical SL/ Van 4... OK (003243-3)
[41/410] Buscando: F-1000 Tropical SL/ Van T... OK (003241-7)
[42/410] Buscando: F-1000 XL 2.5 HSD Diesel ... OK (003167-4)
[43/410] Buscando: F-1000 XL 4.9i           ... OK (003199-2)
[44/410] Buscando: F-1000 XL 4.9i CE        ... OK (003010-4)
[45/410] Buscando: F-1000 XL 4x4 Diesel Turb... OK (003014-7)
[46/410] Buscando: F-1000 XL Diesel Turbo   ... OK (003012-0)
[47/410] Buscando: F-1000 XLT 2.5 HSD Diesel... OK (003168-2)
[48/410] Buscando: F-1000 XLT 4x4 Diesel Tur... OK (003015-5)
[49/410] Buscando: F-1000 XLT CE 4.9i       ... OK (003197-6)
[50/410] Buscando: F-1000 XLT Diesel Turbo  ... OK (003013-9)

💾 Salvando lote de 50 registros no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✔️ Lote salvo com sucesso!

[51/410] Buscando: F-1000 XLT/XL Lighting 4.... OK (003011-2)
[52/410] Buscando: F-150 Lariat 4x4 5.0 V8  ... OK (003489-4)
[53/410] Buscando: F-150 Lariat Black 4x4 5.... OK (003509-2)
[54/410] Buscando: F-150 Platinum 4x4 5.0 V8... OK (003490-8)
[55/410] Buscando: F-150 Tremor 4x4 5.0 V8  ... OK (003512-2)
[56/410] Buscando: F-150 XL Triton 4.3 V6   ... OK (003126-7)
[57/410] Buscando: F-150 XLT Triton 4.3     ... OK (003159-3)
[58/410] Buscando: F-150 XLT Triton 4.6 V8  ... OK (003217-4)
[59/410] Buscando: F-150 XLT Triton 5.8     ... OK (003160-7)
[60/410] Buscando: F-250 F-MILHA CD 3.9 TB D... OK (003338-3)
[61/410] Buscando: F-250 Tropica./Tropmine E... OK (003355-3)
[62/410] Buscando: F-250 TropiCab CE 3.9 TB ... OK (003313-8)
[63/410] Buscando: F-250 Tropical 3.9 Diesel... OK (003170-4)
[64/410] Buscando: F-250 Tropical 4.2 CE / C... OK (003172-0)
[65/410] Buscando: F-250 Tropical 4.2 V6    ... OK (003171-2)
[66/410] Buscando: F-250 Tropical SL/ Van T.... OK (003242-5)
[67/410] Buscando: F-250 Tropicampo CD 3.9 T... OK (003314-6)
[68/410] Buscando: F-250 Tropiclassic 3.9 TB... OK (003315-4)
[69/410] Buscando: F-250 Tropivan Executive ... OK (003316-2)
[70/410] Buscando: F-250 Tropivan/Tropi. Plu... OK (003317-0)
[71/410] Buscando: F-250 XL 3.9 4x2 Diesel  ... OK (003115-1)
[72/410] Buscando: F-250 XL 3.9 4x4 TB Diese... OK (003305-7)
[73/410] Buscando: F-250 XL 3.9 CD TB Diesel... OK (003306-5)
[74/410] Buscando: F-250 XL 4.2 180cv CD TB ... OK (003279-4)
[75/410] Buscando: F-250 XL 4.2 Turbo Diesel... OK (003198-4)
[76/410] Buscando: F-250 XL 4.2 V6          ... OK (003114-3)
[77/410] Buscando: F-250 XL Super Duty 3.9 D... OK (003142-9)
[78/410] Buscando: F-250 XL Super Duty 4.2 T... OK (003272-7)
[79/410] Buscando: F-250 XL Super Duty 4.2 V... OK (003141-0)
[80/410] Buscando: F-250 XLT 3.9 4x2 CD TB D... OK (003308-1)
[81/410] Buscando: F-250 XLT 3.9 4x2 Diesel ... OK (003117-8)
[82/410] Buscando: F-250 XLT 3.9 4x4 CD TB D... OK (003309-0)
[83/410] Buscando: F-250 XLT 3.9 4x4 TB Dies... OK (003307-3)
[84/410] Buscando: F-250 XLT 4.2 180cv CD TB... OK (003280-8)
[85/410] Buscando: F-250 XLT 4.2 TB Diesel  ... OK (003206-9)
[86/410] Buscando: F-250 XLT 4.2 V6         ... OK (003116-0)
[87/410] Buscando: Fiesta 1.0 8V Flex/Class ... OK (003310-3)
[88/410] Buscando: Fiesta 1.0i 3p e 5p      ... OK (003016-3)
[89/410] Buscando: Fiesta 1.3  3p e 5p      ... OK (003075-9)
[90/410] Buscando: Fiesta 1.5 16V Flex Mec. ... OK (003386-3)
[91/410] Buscando: Fiesta 1.6 16V Flex Aut. ... OK (003388-0)
[92/410] Buscando: Fiesta 1.6 16V Flex Mec. ... OK (003387-1)
[93/410] Buscando: Fiesta 1.6 8V Flex/Class ... OK (003286-7)
[94/410] Buscando: Fiesta Class 1.0 2p      ... OK (003200-0)
[95/410] Buscando: Fiesta Class 1.0 4p      ... OK (003201-8)
[96/410] Buscando: Fiesta Class 1.6 8V 98cv ... OK (003261-1)
[97/410] Buscando: Fiesta CLX 1.3i 3p       ... OK (003052-0)
[98/410] Buscando: Fiesta CLX 1.3i 5p       ... OK (003053-8)
[99/410] Buscando: Fiesta CLX 1.4i 16V 3p e ... OK (003017-1)
[100/410] Buscando: Fiesta GL 1.0 3p         ... OK (003143-7)

💾 Salvando lote de 50 registros no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✔️ Lote salvo com sucesso!

[101/410] Buscando: Fiesta GL 1.0 5p         ... OK (003192-5)
[102/410] Buscando: Fiesta GL Class 1.0i 5p  ... OK (003096-1)
[103/410] Buscando: Fiesta GLX 1.6 8V 3p     ... OK (003144-5)
[104/410] Buscando: Fiesta GLX 1.6 8V 5p     ... OK (003193-3)
[105/410] Buscando: Fiesta Personnalité 1.0 8... OK (003259-0)
[106/410] Buscando: Fiesta S 1.0 8V Flex 5p  ... OK (003380-4)
[107/410] Buscando: Fiesta SE 1.0 8V Flex 5p ... OK (003381-2)
[108/410] Buscando: Fiesta SE 1.6 16V Flex 5p... OK (003351-0)
[109/410] Buscando: Fiesta SE 1.6 8V Flex 5p ... OK (003382-0)
[110/410] Buscando: Fiesta SE Plus 1.6 16V Fl... OK (003449-5)
[111/410] Buscando: Fiesta SE Plus Direct 1.6... OK (003437-1)
[112/410] Buscando: Fiesta SE Style 1.6 16V F... OK (003430-4)
[113/410] Buscando: Fiesta Sed. 1.6 8V Flex 4... OK (003289-1)
[114/410] Buscando: Fiesta Sed. Personnalité ... OK (003287-5)
[115/410] Buscando: Fiesta Sed. Supercharger ... OK (003288-3)
[116/410] Buscando: Fiesta Sed. TI./TI.Plus1.... OK (003400-2)
[117/410] Buscando: Fiesta Sedan 1.0 8V Flex ... OK (003311-1)
[118/410] Buscando: Fiesta Sedan 1.6 16V Flex... OK (003398-7)
[119/410] Buscando: Fiesta Sedan 1.6 16V Flex... OK (003397-9)
[120/410] Buscando: Fiesta Sedan S 1.0 8V Fle... OK (003383-9)
[121/410] Buscando: Fiesta Sedan SE 1.0 8V Fl... OK (003384-7)
[122/410] Buscando: Fiesta Sedan SE 1.6 16V F... OK (003340-5)
[123/410] Buscando: Fiesta Sedan SE 1.6 8V Fl... OK (003385-5)
[124/410] Buscando: Fiesta Sedan SEL 1.6 16V ... OK (003443-6)
[125/410] Buscando: Fiesta Sedan SEL 1.6 16V ... OK (003444-4)
[126/410] Buscando: Fiesta Sedan Street 1.0 8... OK (003245-0)
[127/410] Buscando: Fiesta Sedan Street 1.6 8... OK (003246-8)
[128/410] Buscando: Fiesta Sedan TITANIUM 1.6... OK (003399-5)
[129/410] Buscando: Fiesta SEL 1.0 12V EcoBoo... OK (003436-3)
[130/410] Buscando: Fiesta SEL 1.6 16V Flex  ... OK (003423-1)
[131/410] Buscando: Fiesta SEL 1.6 16V Flex M... OK (003422-3)
[132/410] Buscando: Fiesta SEL Style 1.0 EcoB... OK (003450-9)
[133/410] Buscando: Fiesta SEL Style 1.6 16V ... OK (003431-2)
[134/410] Buscando: Fiesta Sport 1.0MPi 4p   ... OK (003219-0)
[135/410] Buscando: Fiesta Sport 1.6 16V Flex... OK (003416-9)
[136/410] Buscando: Fiesta Sport 1.6MPi 4p   ... OK (003221-2)
[137/410] Buscando: Fiesta Street 1.0 8v 3p  ... OK (003229-8)
[138/410] Buscando: Fiesta Street 1.6 8v 95cv... OK (003256-5)
[139/410] Buscando: Fiesta Street/ Action 1.0... OK (003244-1)
[140/410] Buscando: Fiesta Supercharger 1.0 8... OK (003260-3)
[141/410] Buscando: Fiesta TIT./TIT.Plus 1.6 ... OK (003390-1)
[142/410] Buscando: Fiesta TIT.Plus 1.0 12V E... OK (003424-0)
[143/410] Buscando: Fiesta TITANIUM 1.6 16V F... OK (003389-8)
[144/410] Buscando: Fiesta TRAIL 1.0 8V Flex ... OK (003322-7)
[145/410] Buscando: Fiesta TRAIL 1.6 8V Flex ... OK (003323-5)
[146/410] Buscando: Focus 1.6 S/1.6 SE Flex 1... OK (003404-5)
[147/410] Buscando: Focus 1.6 S/SE/SE Plus Fl... OK (003281-6)
[148/410] Buscando: Focus 1.8 16V 5p         ... OK (003224-7)
[149/410] Buscando: Focus 2.0 16V/ 2.0 16V Fl... OK (003228-0)
[150/410] Buscando: Focus 2.0 16V/SE/SE Plus ... OK (003283-2)

💾 Salvando lote de 50 registros no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✔️ Lote salvo com sucesso!

[151/410] Buscando: Focus Fastback SE/SE PLUS... OK (003417-7)
[152/410] Buscando: Focus Fastback TIT./T.PLU... OK (003418-5)
[153/410] Buscando: Focus Ghia  2.0 16V/ 2.0 ... OK (003266-2)
[154/410] Buscando: Focus Ghia Sed. 2.0 16V/ ... OK (003226-3)
[155/410] Buscando: Focus Ghia Sed. 2.0 16V/2... OK (003262-0)
[156/410] Buscando: Focus Ghia/ XR 2.0 /Ghia ... OK (003227-1)
[157/410] Buscando: Focus Sed. TI./TI.Plus 2.... OK (003348-0)
[158/410] Buscando: Focus Sedan 1.6 16V Flex ... OK (003425-8)
[159/410] Buscando: Focus Sedan 1.6/1.6 Flex ... OK (003284-0)
[160/410] Buscando: Focus Sedan 1.8 16V 115cv... OK (003265-4)
[161/410] Buscando: Focus Sedan 2.0 16V/2.0 1... OK (003225-5)
[162/410] Buscando: Focus Sedan 2.0 16V/2.0 1... OK (003282-4)
[163/410] Buscando: Focus TITA/TITA Plus 2.0 ... OK (003347-2)
[164/410] Buscando: Focus TITANIUM 2.0 16V Fl... OK (003346-4)
[165/410] Buscando: Furglaine 3.6            ... OK (003173-9)
[166/410] Buscando: Furglaine 3.9 Diesel     ... OK (003174-7)
[167/410] Buscando: Furglaine Chateaux/Exec. ... OK (003175-5)
[168/410] Buscando: Fusion 2.5 16V 193cv Aut.... OK (003345-6)
[169/410] Buscando: Fusion 2.5L I-VCT Flex Au... OK (003378-2)
[170/410] Buscando: Fusion SE 2.5 I-VCT Flex ... OK (003432-0)
[171/410] Buscando: Fusion SEL 2.0 Ecobo. 16V... OK (003429-0)
[172/410] Buscando: Fusion SEL 2.3 16V  162cv... OK (003304-9)
[173/410] Buscando: Fusion SEL 2.5 16V 173cv ... OK (003335-9)
[174/410] Buscando: Fusion SEL 3.0 V6  24V 24... OK (003349-9)
[175/410] Buscando: Fusion SEL 3.0 V6 AWD 24V... OK (003336-7)
[176/410] Buscando: Fusion Titanium 2.0 145cv... OK (003402-9)
[177/410] Buscando: Fusion Titanium 2.0 GTDI ... OK (003376-6)
[178/410] Buscando: Fusion Titanium 2.0 GTDI ... OK (003377-4)
[179/410] Buscando: Ibiza 3.9 Furgão Diesel  ... OK (003176-3)
[180/410] Buscando: Ibiza Chat./Exec. 3.9 Die... OK (003177-1)
[181/410] Buscando: Ka 1.0 8V/1.0 8V ST Flex ... OK (003325-1)
[182/410] Buscando: Ka 1.0 FREESTYLE 12V Flex... OK (003473-8)
[183/410] Buscando: Ka 1.0 S TiVCT Flex 5p   ... OK (003448-7)
[184/410] Buscando: Ka 1.0 SE/SE Plus TiVCT F... OK (003408-8)
[185/410] Buscando: Ka 1.0 SEL TiVCT Flex 5p ... OK (003409-6)
[186/410] Buscando: Ka 1.0 TECNO 12V Flex 5p ... OK (003447-9)
[187/410] Buscando: Ka 1.0 TECNO 8V Flex 3p  ... OK (003327-8)
[188/410] Buscando: Ka 1.0i 3p               ... OK (003018-0)
[189/410] Buscando: Ka 1.5 100 Anos Flex 5p A... OK (003471-1)
[190/410] Buscando: Ka 1.5 FreeStyle 12V Flex... OK (003457-6)
[191/410] Buscando: Ka 1.5 FreeStyle 12V Flex... OK (003458-4)
[192/410] Buscando: Ka 1.5 SE 12V Flex 5p Aut... OK (003459-2)
[193/410] Buscando: Ka 1.5 SE 12V Flex 5p Mec... OK (003462-2)
[194/410] Buscando: Ka 1.5 SE Plus 12V Flex 5... OK (003460-6)
[195/410] Buscando: Ka 1.5 SE Plus 12V Flex 5... OK (003461-4)
[196/410] Buscando: Ka 1.5 SE/SE PLUS 16V Fle... OK (003410-0)
[197/410] Buscando: Ka 1.5 Sedan SE 12V Flex ... OK (003464-9)
[198/410] Buscando: Ka 1.5 Sedan SE 12V Flex ... OK (003463-0)
[199/410] Buscando: Ka 1.5 Sedan SE Plus 12V ... OK (003465-7)
[200/410] Buscando: Ka 1.5 Sedan SE Plus 12V ... OK (003466-5)

💾 Salvando lote de 50 registros no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✔️ Lote salvo com sucesso!

[201/410] Buscando: Ka 1.5 Sedan SEL 12V Flex... OK (003474-6)
[202/410] Buscando: Ka 1.5 Sedan SEL 12V Flex... OK (003468-1)
[203/410] Buscando: Ka 1.5 Sedan TITANIUM 12V... OK (003456-8)
[204/410] Buscando: Ka 1.5 TITANIUM 12V Flex ... OK (003467-3)
[205/410] Buscando: Ka 1.6 8V Flex 3p        ... OK (003326-0)
[206/410] Buscando: Ka 1.6 TECNO 8V Flex 3p  ... OK (003328-6)
[207/410] Buscando: Ka Action 1.6 MPI 8V 95cv... OK (003264-6)
[208/410] Buscando: Ka Black 1.0 MPI 8v 65cv ... OK (003233-6)
[209/410] Buscando: Ka Black 1.6 MPI 8v 95cv ... OK (003234-4)
[210/410] Buscando: Ka CLX 1.3i 3p           ... OK (003019-8)
[211/410] Buscando: Ka GL 1.0i Zetec Rocam   ... OK (003145-3)
[212/410] Buscando: Ka GL Image 1.0i/ 1.0i Ze... OK (003161-5)
[213/410] Buscando: Ka Image 1.0i            ... OK (003098-8)
[214/410] Buscando: Ka MP3 1.0 MPI 8V 65cv   ... OK (003301-4)
[215/410] Buscando: Ka MP3 1.6 MPI 8V 95cv   ... OK (003302-2)
[216/410] Buscando: Ka SEL 1.5 16V Flex 5p   ... OK (003411-8)
[217/410] Buscando: Ka Sport 1.6 8V Flex 3p  ... OK (003350-2)
[218/410] Buscando: Ka Street 1.0i           ... OK (003097-0)
[219/410] Buscando: Ka Tecno 1.0i 8v Zetec Ro... OK (003169-0)
[220/410] Buscando: Ka TRAIL 1.0 12V Flex Mec... OK (003435-5)
[221/410] Buscando: Ka TRAIL 1.5 16V Flex Mec... OK (003434-7)
[222/410] Buscando: Ka XR 1.6 MPI 8V         ... OK (003232-8)
[223/410] Buscando: Ka+ Sedan 1.0 SE/SE PLUS ... OK (003412-6)
[224/410] Buscando: Ka+ Sedan 1.0 SEL TiCVT F... OK (003413-4)
[225/410] Buscando: Ka+ Sedan 1.5 ADVANCED 16... OK (003446-0)
[226/410] Buscando: Ka+ Sedan 1.5 SE/SE PLUS ... OK (003414-2)
[227/410] Buscando: Ka+ Sedan 1.5 SEL 16V Fle... OK (003415-0)
[228/410] Buscando: Maverick L. Black 2.0 Eco... OK (003510-6)
[229/410] Buscando: Maverick Lariat FX4 2.0 E... OK (003485-1)
[230/410] Buscando: Maverick Lariat Hybrid 2.... OK (003518-1)
[231/410] Buscando: Maverick Lariat Hybrid 2.... OK (003495-9)
[232/410] Buscando: Maverick Tremor 2.0 EcoBo... OK (003511-4)
[233/410] Buscando: Mondeo CLX 1.8 4p e 5p   ... OK (003076-7)
[234/410] Buscando: Mondeo CLX 1.8i SW       ... OK (003077-5)
[235/410] Buscando: Mondeo CLX 2.0i 4p Aut   ... OK (003194-1)
[236/410] Buscando: Mondeo CLX 2.0i 4p Mec   ... OK (003078-3)
[237/410] Buscando: Mondeo CLX 2.0i SW Aut   ... OK (003195-0)
[238/410] Buscando: Mondeo CLX 2.0i SW Mec   ... OK (003079-1)
[239/410] Buscando: Mondeo Ghia 2.0 16V 143cv... OK (003258-1)
[240/410] Buscando: Mondeo Ghia 2.0 16V 143cv... OK (003257-3)
[241/410] Buscando: Mondeo Ghia 2.5 V6 Aut   ... OK (003104-6)
[242/410] Buscando: Mondeo Ghia 2.5 V6 Mec   ... OK (003103-8)
[243/410] Buscando: Mondeo GLX 2.0 16V 4p Aut... OK (003223-9)
[244/410] Buscando: Mondeo GLX 2.0 4p e 5p   ... OK (003080-5)
[245/410] Buscando: Mondeo GLX 2.0i SW Mec./ ... OK (003082-1)
[246/410] Buscando: Mustang 3.8 V6           ... OK (003179-8)
[247/410] Buscando: Mustang 3.8 V6 Conv.     ... OK (003180-1)
[248/410] Buscando: Mustang Black Shadow 5.0 ... OK (003475-4)
[249/410] Buscando: Mustang Cobra 5.7 V8     ... OK (003190-9)
[250/410] Buscando: Mustang Dark Horse 5.0 V8... OK (003516-5)

💾 Salvando lote de 50 registros no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✔️ Lote salvo com sucesso!

[251/410] Buscando: Mustang GT Performance 5.... OK (003507-6)
[252/410] Buscando: Mustang GT Performance 5.... OK (003515-7)
[253/410] Buscando: Mustang GT Premium 5.0 V8... OK (003453-3)
[254/410] Buscando: Mustang GT V8            ... OK (003083-0)
[255/410] Buscando: Mustang GT V8 Conversível... OK (003084-8)
[256/410] Buscando: Mustang MACH 1 5.0 V8    ... OK (003480-0)
[257/410] Buscando: Mustang Mach-E GT Perform... OK (003505-0)
[258/410] Buscando: Pampa 4x4 Jeep GL / L 1.6... OK (003058-9)
[259/410] Buscando: Pampa Ghia 1.6/1.8/DUO   ... OK (003137-2)
[260/410] Buscando: Pampa GL 1.6/ 1.8        ... OK (003056-2)
[261/410] Buscando: Pampa L 1.6              ... OK (003054-6)
[262/410] Buscando: Pampa L 1.8i / 1.8       ... OK (003055-4)
[263/410] Buscando: Pampa S 1.8              ... OK (003057-0)
[264/410] Buscando: Probe 2.0/2.2            ... OK (003125-9)
[265/410] Buscando: Probe GT 2.5 V6          ... OK (003182-8)
[266/410] Buscando: Ranger 2.5 4x2 CD TB Dies... OK (003210-7)
[267/410] Buscando: Ranger 2.5 4x2 CE Diesel ... OK (003209-3)
[268/410] Buscando: Ranger 2.5 4x2 TB Diesel ... OK (003205-0)
[269/410] Buscando: Ranger 2.5 4x4 CD TB Dies... OK (003108-9)
[270/410] Buscando: Ranger 2.5 4x4 CE TB Dies... OK (003147-0)
[271/410] Buscando: Ranger 2.5 4x4 TB Diesel ... OK (003107-0)
[272/410] Buscando: Ranger 2.5i CD           ... OK (003105-4)
[273/410] Buscando: Ranger 2.5i CE           ... OK (003146-1)
[274/410] Buscando: Ranger 2.5i CS           ... OK (003106-2)
[275/410] Buscando: Ranger Black 2.0 4x2 CD T... OK (003508-4)
[276/410] Buscando: Ranger Black 2.2 4x2 CD D... OK (003479-7)
[277/410] Buscando: Ranger FX4 3.2 20V 4x4 CD... OK (003486-0)
[278/410] Buscando: Ranger Limited 2.3 150cv ... OK (003337-5)
[279/410] Buscando: Ranger Limited 2.5 16V 4x... OK (003359-6)
[280/410] Buscando: Ranger Limited 3.0 PSE 4x... OK (003296-4)
[281/410] Buscando: Ranger Limited 3.0 V6 4x4... OK (003497-5)
[282/410] Buscando: Ranger Limited 3.2 4x4 CD... OK (003364-2)
[283/410] Buscando: Ranger Limited+ 3.0 V6 4x... OK (003498-3)
[284/410] Buscando: Ranger Raptor 3.0 V6 Bi-T... OK (003506-8)
[285/410] Buscando: Ranger Splash CE         ... OK (003220-4)
[286/410] Buscando: Ranger Splash CS         ... OK (003089-9)
[287/410] Buscando: Ranger SPORT 2.5 Flex 16V... OK (003406-1)
[288/410] Buscando: Ranger SPORTRAC 2.2 16V 4... OK (003445-2)
[289/410] Buscando: Ranger Storm 3.2 20V 4x4 ... OK (003476-2)
[290/410] Buscando: Ranger STX 4.0 CS/ CE    ... OK (003090-2)
[291/410] Buscando: Ranger TROPICAB 2.5 16V 4... OK (003396-0)
[292/410] Buscando: Ranger TROPICAB 3.2 20V 4... OK (003395-2)
[293/410] Buscando: Ranger TROPIVAN 2.5 16V 4... OK (003394-4)
[294/410] Buscando: Ranger TROPIVAN 3.2 20V 4... OK (003393-6)
[295/410] Buscando: Ranger TROPIVAN 3.2 20V 4... OK (003392-8)
[296/410] Buscando: Ranger TROPIVAN XLT 2.3 1... OK (003341-3)
[297/410] Buscando: Ranger TROPIVAN XLT 3.0 P... OK (003342-1)
[298/410] Buscando: Ranger TROPIVAN XLT 3.0 P... OK (003343-0)
[299/410] Buscando: Ranger XL 2.0 4x4 CD Dies... OK (003502-5)
[300/410] Buscando: Ranger XL 2.2 4x4 CD Dies... OK (003426-6)

💾 Salvando lote de 50 registros no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✔️ Lote salvo com sucesso!

[301/410] Buscando: Ranger XL 2.2 4x4 CS Dies... OK (003433-9)
[302/410] Buscando: Ranger XL 2.3 16v 137cv 4... OK (003237-9)
[303/410] Buscando: Ranger XL 2.3 16v 137cv 4... OK (003236-0)
[304/410] Buscando: Ranger XL 2.3 16v 137cv 4... OK (003235-2)
[305/410] Buscando: Ranger XL 2.3 CS         ... OK (003085-6)
[306/410] Buscando: Ranger XL 2.8 8v 135cv 4x... OK (003254-9)
[307/410] Buscando: Ranger XL 2.8 8v 135cv 4x... OK (003249-2)
[308/410] Buscando: Ranger XL 2.8 8v 135cv 4x... OK (003247-6)
[309/410] Buscando: Ranger XL 2.8 8v 135cv 4x... OK (003255-7)
[310/410] Buscando: Ranger XL 2.8 8v 135cv 4x... OK (003250-6)
[311/410] Buscando: Ranger XL 2.8 8v 135cv 4x... OK (003248-4)
[312/410] Buscando: Ranger XL 3.0 PSE 163cv 4... OK (003298-0)
[313/410] Buscando: Ranger XL 3.0 PSE 163cv 4... OK (003299-9)
[314/410] Buscando: Ranger XL 3.0 PSE 163cv 4... OK (003300-6)
[315/410] Buscando: Ranger XL 3.0 PSE 163cv 4... OK (003297-2)
[316/410] Buscando: Ranger XL 4.0 12v V6 210c... OK (003238-7)
[317/410] Buscando: Ranger XL 4.0 CS         ... OK (003086-4)
[318/410] Buscando: Ranger XLS 2.0 4x2 CD Die... OK (003499-1)
[319/410] Buscando: Ranger XLS 2.0 4x4 CD Die... OK (003501-7)
[320/410] Buscando: Ranger XLS 2.2 4x2 CD Die... OK (003454-1)
[321/410] Buscando: Ranger XLS 2.2 4x2 CD Die... OK (003442-8)
[322/410] Buscando: Ranger XLS 2.2 4x4 CD Die... OK (003421-5)
[323/410] Buscando: Ranger XLS 2.2 4x4 CD Die... OK (003405-3)
[324/410] Buscando: Ranger XLS 2.3 16V 145cv/... OK (003276-0)
[325/410] Buscando: Ranger XLS 2.3 16V 145cv/... OK (003275-1)
[326/410] Buscando: Ranger XLS 2.5 16V 4x2 CD... OK (003357-0)
[327/410] Buscando: Ranger XLS 2.5 16V 4x2 CS... OK (003356-1)
[328/410] Buscando: Ranger XLS 2.8 8V 135cv 4... OK (003278-6)
[329/410] Buscando: Ranger XLS 2.8 8V 135cv 4... OK (003277-8)
[330/410] Buscando: Ranger XLS 2.8 8V 135cv 4... OK (003273-5)
[331/410] Buscando: Ranger XLS 2.8/2.8 Storm ... OK (003274-3)
[332/410] Buscando: Ranger XLS 3.0 PSE 163cv ... OK (003291-3)
[333/410] Buscando: Ranger XLS 3.0 PSE 163cv ... OK (003292-1)
[334/410] Buscando: Ranger XLS 3.0 PSE 163cv ... OK (003293-0)
[335/410] Buscando: Ranger XLS 3.0 PSE Storm ... OK (003334-0)
[336/410] Buscando: Ranger XLS 3.0 V6 4x4 CD ... OK (003500-9)
[337/410] Buscando: Ranger XLS 3.2 20V 4x4 CD... OK (003401-0)
[338/410] Buscando: Ranger XLS 3.2 20V 4x4 CD... OK (003361-8)
[339/410] Buscando: Ranger XLS 3.2 20V 4x4 CS... OK (003360-0)
[340/410] Buscando: Ranger XLS SPORT 2.3 16V ... OK (003324-3)
[341/410] Buscando: Ranger XLT 2.3 16V 150cv ... OK (003321-9)
[342/410] Buscando: Ranger XLT 2.3 CS        ... OK (003087-2)
[343/410] Buscando: Ranger XLT 2.5 16V 4x2 CD... OK (003358-8)
[344/410] Buscando: Ranger XLT 2.5 4x2 CD Die... OK (003204-2)
[345/410] Buscando: Ranger XLT 2.5 4x2 CE Die... OK (003202-6)
[346/410] Buscando: Ranger XLT 2.5 4x2 CS Die... OK (003203-4)
[347/410] Buscando: Ranger XLT 2.5 4x4 CD Die... OK (003110-0)
[348/410] Buscando: Ranger XLT 2.5 4x4 CE TB ... OK (003148-8)
[349/410] Buscando: Ranger XLT 2.5 4x4 CS TB ... OK (003109-7)
[350/410] Buscando: Ranger XLT 2.8 8v 135cv 4... OK (003252-2)

💾 Salvando lote de 50 registros no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✔️ Lote salvo com sucesso!

[351/410] Buscando: Ranger XLT 2.8 8v 135cv 4... OK (003253-0)
[352/410] Buscando: Ranger XLT 2.8 8v 135cv 4... OK (003251-4)
[353/410] Buscando: Ranger XLT 3.0 PSE 163cv ... OK (003294-8)
[354/410] Buscando: Ranger XLT 3.0 PSE 163cv ... OK (003295-6)
[355/410] Buscando: Ranger XLT 3.0 V6 4x4 CD ... OK (003496-7)
[356/410] Buscando: Ranger XLT 3.2 20V 4x4 CD... OK (003362-6)
[357/410] Buscando: Ranger XLT 3.2 20V 4x4 CD... OK (003363-4)
[358/410] Buscando: Ranger XLT 4.0 12v V6 210... OK (003240-9)
[359/410] Buscando: Ranger XLT 4.0 12v V6 210... OK (003239-5)
[360/410] Buscando: Ranger XLT 4.0 4x2 CE    ... OK (003149-6)
[361/410] Buscando: Ranger XLT 4.0 4x2 CS    ... OK (003088-0)
[362/410] Buscando: Ranger XLT 4.0 4x4 CD    ... OK (003112-7)
[363/410] Buscando: Ranger XLT 4.0 4x4 CE    ... OK (003150-0)
[364/410] Buscando: Ranger XLT 4.0 4x4 CS    ... OK (003111-9)
[365/410] Buscando: Ranger XLT Limit./L.Cent.... OK (003263-8)
[366/410] Buscando: Royale Ghia 2.0/2.0i 2p e... OK (003061-9)
[367/410] Buscando: Royale GL 1.8/1.8i  2p e ... OK (003059-7)
[368/410] Buscando: Royale GL 2.0/2.0i 2p e 4... OK (003060-0)
[369/410] Buscando: Taurus GL 3.0 V6         ... OK (003091-0)
[370/410] Buscando: Taurus GL SW 3.0 V6 24V  ... OK (003127-5)
[371/410] Buscando: Taurus L/LX 3.0 V6       ... OK (003092-9)
[372/410] Buscando: Taurus LX SW 3.0 V6 24V  ... OK (003191-7)
[373/410] Buscando: Taurus SHO 3.0 V6        ... OK (003183-6)
[374/410] Buscando: TERRITORY SEL 1.5 GTDi Ec... OK (003477-0)
[375/410] Buscando: TERRITORY Titanium 1.5 GT... OK (003478-9)
[376/410] Buscando: Thunderbird SC 3.8 V6    ... OK (003184-4)
[377/410] Buscando: TRANSIT Chassi 2.2 TDCI D... OK (003372-3)
[378/410] Buscando: TRANSIT Chassi 2.4 TDCI D... OK (003339-1)
[379/410] Buscando: TRANSIT Chassi 350E 2.0 E... OK (003503-3)
[380/410] Buscando: TRANSIT Chassi 470E 2.0 E... OK (003504-1)
[381/410] Buscando: TRANSIT Furgão 2.0 Longo ... OK (003494-0)
[382/410] Buscando: TRANSIT Furgão 2.0 Longo ... OK (003488-6)
[383/410] Buscando: TRANSIT Furgão 2.0 Medio ... OK (003517-3)
[384/410] Buscando: TRANSIT Furgão 2.0 Medio ... OK (003487-8)
[385/410] Buscando: TRANSIT Furgão 2.2 TDCI C... OK (003379-0)
[386/410] Buscando: TRANSIT Furgão 2.2 TDCI L... OK (003375-8)
[387/410] Buscando: TRANSIT Furgão 2.2 TDCI L... OK (003354-5)
[388/410] Buscando: TRANSIT Furgão 3330 2.4 T... OK (003331-6)
[389/410] Buscando: TRANSIT Furgão 3550 2.4 T... OK (003332-4)
[390/410] Buscando: TRANSIT Minibus 15 Lug. 2... OK (003491-6)
[391/410] Buscando: TRANSIT Minibus 15 Lug. 2... OK (003483-5)
[392/410] Buscando: TRANSIT Minibus 18 Lug. 2... OK (003492-4)
[393/410] Buscando: TRANSIT Minibus 18 Lug. 2... OK (003484-3)
[394/410] Buscando: TRANSIT Minibus Vidrada 2... OK (003493-2)
[395/410] Buscando: TRANSIT Minibus Vidrada 2... OK (003482-7)
[396/410] Buscando: TRANSIT Van 3550 2.2 TDCI... OK (003371-5)
[397/410] Buscando: TRANSIT Van 3550 2.4 TDCI... OK (003333-2)
[398/410] Buscando: Verona Ghia 2.0i 4p      ... OK (003065-1)
[399/410] Buscando: Verona GL 1.8i / LX 1.8i ... OK (003062-7)
[400/410] Buscando: Verona GLX 1.8 (Modelo an... OK (003069-4)

💾 Salvando lote de 50 registros no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✔️ Lote salvo com sucesso!

[401/410] Buscando: Verona GLX 1.8i / 1.8 4p ... OK (003063-5)
[402/410] Buscando: Verona GLX 2.0i / 2.0 4p ... OK (003064-3)
[403/410] Buscando: Verona LX 1.6 (Modelo ant... OK (003067-8)
[404/410] Buscando: Verona LX 1.8 (Modelo ant... OK (003068-6)
[405/410] Buscando: Verona S 2.0i 4p         ... OK (003066-0)
[406/410] Buscando: Versailles Ghia 2.0i / 2.... OK (003072-4)
[407/410] Buscando: Versailles GL 1.8i / 1.8 ... OK (003070-8)
[408/410] Buscando: Versailles GL 2.0i / 2.0 ... OK (003071-6)
[409/410] Buscando: Windstar GL              ... OK (003093-7)
[410/410] Buscando: Windstar LX              ... OK (003094-5)

💾 Salvando lote final de 10 registros no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

✔️ Último lote salvo com sucesso!

In [52]:
query = f"""
    SELECT *
    FROM 
        `{PROJECT_ID}.analytics_ford.modelos_com_fipe`

"""
    
# 3. Executar a consulta (Job)
# query_job = client.query(query)
    
  
df_resultado = client.query(query).to_dataframe()
    


df_resultado

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,tipo_veiculo,marca_codigo,modelo_codigo,modelo_nome,codigo_fipe
0,carros,22,916,Verona GLX 1.8i / 1.8 4p,003063-5
1,carros,22,917,Verona GLX 2.0i / 2.0 4p,003064-3
2,carros,22,918,Verona LX 1.6 (Modelo antigo),003067-8
3,carros,22,919,Verona LX 1.8 (Modelo antigo),003068-6
4,carros,22,920,Verona S 2.0i 4p,003066-0
...,...,...,...,...,...
646,carros,22,887,Ranger XLT 2.5 4x2 CS Diesel,003203-4
647,carros,22,888,Ranger XLT 2.5 4x4 CD Diesel,003110-0
648,carros,22,889,Ranger XLT 2.5 4x4 CE TB Diesel,003148-8
649,carros,22,890,Ranger XLT 2.5 4x4 CS TB Diesel,003109-7
650,carros,22,891,Ranger XLT 2.8 8v 135cv 4x2 CD TB Diesel,003252-2

In [53]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

# ==========================================
# 1. CONFIGURAÇÃO
# ==========================================
load_dotenv()
client = bigquery.Client()

project_id = client.project 

DB_NAME = "analytics_ford"
TABELA_DESTINO = f"{project_id}.{DB_NAME}.referencia_meses_fipe"

# Dicionário para "traduzir" o mês em texto para número e abreviação
MAPEAMENTO_MESES = {
    'janeiro':   ('01', 'jan'),
    'fevereiro': ('02', 'fev'),
    'março':     ('03', 'mar'),
    'abril':     ('04', 'abr'),
    'maio':      ('05', 'mai'),
    'junho':     ('06', 'jun'),
    'julho':     ('07', 'jul'),
    'agosto':    ('08', 'ago'),
    'setembro':  ('09', 'set'),
    'outubro':   ('10', 'out'),
    'novembro':  ('11', 'nov'),
    'dezembro':  ('12', 'dez')
}

# ==========================================
# 2. PREPARAR INFRAESTRUTURA
# ==========================================
def preparar_tabela_referencia():
    """Garante que a tabela de referência exista."""
    schema = [
        bigquery.SchemaField("codigo", "INT64", mode="REQUIRED", description="Código oficial da Tabela Fipe"),
        bigquery.SchemaField("descricao_original", "STRING", mode="REQUIRED", description="Ex: abril/2026"),
        bigquery.SchemaField("ano", "INT64", mode="REQUIRED"),
        bigquery.SchemaField("mes", "STRING", mode="REQUIRED", description="Mês em formato numérico (01 a 12)"),
        bigquery.SchemaField("mes_abrev", "STRING", mode="REQUIRED", description="Abreviação do mês (jan, fev...)"),
    ]
    try:
        client.get_table(TABELA_DESTINO)
        print(f"✅ Tabela {TABELA_DESTINO} já existe.")
    except NotFound:
        table = bigquery.Table(TABELA_DESTINO, schema=schema)
        client.create_table(table)
        print(f"✨ Tabela {TABELA_DESTINO} criada com sucesso.")

# ==========================================
# 3. EXTRAÇÃO E TRANSFORMAÇÃO (PANDAS)
# ==========================================
def extrair_e_transformar_referencias():
    url = "https://brasilapi.com.br/api/fipe/tabelas/v1"
    print("Buscando dados na BrasilAPI...")
    
    response = requests.get(url)
    response.raise_for_status()
    
    # Transforma o JSON direto em DataFrame
    df = pd.DataFrame(response.json())
    
    print("Limpando e transformando os dados...")
    
    # 1. Limpa espaços invisíveis que possam vir da API (ex: "abril/2026 ")
    df['descricao_original'] = df['mes'].str.strip()
    
    # 2. Quebra a coluna no símbolo '/' em duas novas colunas (nome_mes e ano_texto)
    df[['nome_mes', 'ano_texto']] = df['descricao_original'].str.lower().str.split('/', expand=True)
    
    # 3. Mapeia o nome do mês para pegar a tupla (numero, abreviação)
    # Se por acaso vier um mês que não conhecemos, coloca nulo
    df['dados_mes'] = df['nome_mes'].map(MAPEAMENTO_MESES)
    
    # 4. Extrai os dados da tupla para colunas separadas
    df['mes'] = df['dados_mes'].apply(lambda x: x[0] if pd.notnull(x) else '00')
    df['mes_abrev'] = df['dados_mes'].apply(lambda x: x[1] if pd.notnull(x) else 'unk')
    
    # 5. Converte os tipos (Ano e Código são inteiros)
    df['ano'] = df['ano_texto'].astype(int)
    df['codigo'] = df['codigo'].astype(int)
    
    # 6. Filtra apenas as colunas que vamos salvar e na ordem certa
    df_final = df[['codigo', 'descricao_original', 'ano', 'mes', 'mes_abrev']]
    
    return df_final

# ==========================================
# 4. EXECUÇÃO PRINCIPAL
# ==========================================
def executar():
    preparar_tabela_referencia()
    
    df_resultado = extrair_e_transformar_referencias()
    print(f"\nAmostra dos dados transformados ({len(df_resultado)} linhas no total):")
    print(df_resultado.head())
    
    print("\nSalvando no BigQuery...")
    # ATENÇÃO: Como esta é uma tabela de referência oficial que atualiza todo mês,
    # usamos WRITE_TRUNCATE. Isso apaga a antiga e salva a nova zerada.
    # Assim você nunca tem códigos duplicados!
    job_config = bigquery.LoadJobConfig(write_disposition="WRITE_TRUNCATE")
    
    job = client.load_table_from_dataframe(df_resultado, TABELA_DESTINO, job_config=job_config)
    job.result()
    
    print(f"🎉 Sucesso! Tabela de referência atualizada.")

if __name__ == "__main__":
    executar()

✨ Tabela ford-493401.analytics_ford.referencia_meses_fipe criada com sucesso.
Buscando dados na BrasilAPI...
Limpando e transformando os dados...

Amostra dos dados transformados (304 linhas no total):
   codigo descricao_original   ano mes mes_abrev
0     332         abril/2026  2026  04       abr
1     331         março/2026  2026  03       mar
2     330     fevereiro/2026  2026  02       fev
3     329       janeiro/2026  2026  01       jan
4     328      dezembro/2025  2025  12       dez

Salvando no BigQuery...

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

🎉 Sucesso! Tabela de referência atualizada.

In [ ]:
query = f"""
    SELECT *
    FROM 
        `{PROJECT_ID}.analytics_ford.referencia_meses_fipe`

"""
    
# 3. Executar a consulta (Job)
# query_job = client.query(query)
    
  
df_resultado = client.query(query).to_dataframe()
    


df_resultado

c:\Users\guilh\Documents\Project\Ford\venv\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

     codigo descricao_original   ano mes mes_abrev
0       332         abril/2026  2026  04       abr
1       320         abril/2025  2025  04       abr
2       308         abril/2024  2024  04       abr
3       296         abril/2023  2023  04       abr
4       284         abril/2022  2022  04       abr
..      ...                ...   ...  ..       ...
299      55      setembro/2009  2009  09       set
300      43      setembro/2008  2008  09       set
301      30      setembro/2007  2007  09       set
302      16      setembro/2006  2006  09       set
303       1      setembro/2005  2005  09       set

[304 rows x 5 columns]

: