In [11]:
from youtube_transcript_api import YouTubeTranscriptApi

video_id = 'BmYsInLDmrI'

# 1. Cria a instância da API
youtube_api = YouTubeTranscriptApi()

try:
    # 2. Lista as transcrições disponíveis
    transcript_list = youtube_api.list(video_id)
    
    # 3. Encontra a transcrição (preferencialmente em português)
    transcript = transcript_list.find_transcript(['pt', 'en'])
    
    # 4. Busca os dados
    # O .fetch() retorna uma lista de dicionários padrão
    texto_dados = transcript.fetch()
    
    # 5. Exibe o resultado
    for item in texto_dados:
        # Se for dicionário, item['text'] funciona. 
        # Se for objeto, item.text funcionará.
        texto = item.get('text') if isinstance(item, dict) else item.text
        tempo = item.get('start') if isinstance(item, dict) else item.start
        print(f"{tempo}: {texto}")

except Exception as e:
    print(f"Erro ao processar: {e}")

0.28: Esse é o novo Ford Territory
6.24: 2025. Mudou tudo, agora anda de verdade.
10.16: É um dos maiores espaços internos da
13.08: categoria. Mas será que tem preço e
15.92: condições para bater de frente com os
18.84: outros chineses?
23.32: Não, você não me escutou errado, não.
26.72: Esse, apesar de ter o emblema da Ford,
28.96: vem da China. O SUV de entrada agora da
32.32: Ford no Brasil, mas que não é feito pela
35.399: Ford. E além disso, vale a pena dizer
37.84: que esse carro lá fora já ganhou o
41.0: facelift e virou híbrido. Aqui também
43.96: vai ser igual no vídeo de hoje a gente
45.52: vai ver tudo sobre essa máquina aqui.
47.52: Vamos falar da motorização, vamos falar
50.16: do câmbio do espaço interno que ele dá
52.32: um banho nos outros da categoria do
54.52: porta presuntos. E é claro que a gente
55.96: vai levar essa máquina, dar um rolê e
57.359: ver qual é que é. E é claro que não tem
59.28: lugar melhor pra gente começar a falar
61.359: do Forge Territory, do que aqui a parte
63.6: da frente também que eu escrito pelas
64.68: pessoas mais legais do mundo, como a
66.08: frenteira, bem bonito, né? Azulzinho
67.84: também é covardia. Eu adoro o carro
69.92: azul. Bem bonito, bem bonito. Conjunto
72.88: ótico aqui, tudo LED, bem legal, bem
75.56: bacana, mas que interessa pra gente aqui
77.28: motorização. E abrindo aqui então temos
79.36: acesso ao coração da fera. Manta
81.799: acústica de belíssima qualidade, braços
83.84: pantográficos. Aí sim, eu gostei. Motor
86.72: é 1.5 turbo com injeção direta, porém só
91.119: a gasolina é importado, né? Fazer o quê?
93.68: E é corrente, tá? Corrente de comando.
96.119: Não é correia dentada, muito menos
97.96: banhada a óleo. São 169 ui cavalos e
102.479: 25,4 de torque a 1500 giros. O que rola
107.04: que eu sou um carro bem pesado, 1705 kg,
110.479: 10 a mais sua sogra depois da feijoada,
112.28: garantindo uma relação peso, potência de
113.92: 10 kg para cada cavalinho. Tudo isso com
118.039: câmbio automatizado de dupla embreagem,
120.719: porém banhado a óleo de sete
122.479: velocidades. Não, não é o power shift,
124.68: fica tranquilo. Velocidade máxima de 180
127.36: km/h e 0 a 100 de 10 segundos. É isso. É
131.599: um motor OK, porém um carro é pesado e é
134.319: um motor que é só usado nele, o que
136.239: talvez daqui um tempo manutenção, né?
139.48: Enfim. E finalmente chegamos aqui na
141.76: belíssima traseira do Ford Zoris. Somos
145.4: brasileiros, gostamos de traseira assim
147.16: bem bonita, né? O conjunto ótico, tudo
149.56: LED aqui também. O que eu não gosto que
151.8: a tampa termina muito rente aqui, né, do
153.599: para-choque. Vai entender. Para abrir
155.879: aqui, você pode abrir na chave ou só
157.48: apertar aqui o botãozinho que o
159.4: porta-mala se abre para você. E temos
161.959: aqui acesso ao belíssimo porta-mala. São
164.4: 440 L, todo forradinha. Quando você tira
166.519: e coloca a mala, é forrado também.
168.84: Lembrando, né, que SUV mede-se só até
171.08: aqui. Então, tecnicamente você tem mais
172.92: espaço. Mas se você precisar de mais
174.72: espaço ainda, você pode dobrar os bancos
176.72: aí só para 100. L. Dá para você levar
179.4: uns 14 presuntos. que eles vão no
182.12: conforto. Temos suspensão independente e
184.2: vão livre do solo de 18 cm. A hora que
187.799: você vai ver o step, é bicicletinha
190.599: diferente das belíssimas rodas de liga
192.879: leve aqui com freio a disco nas quatro
195.56: rodas. Preço oficial R$ 215.000as.
200.879: Tem culpa? Eu não, mas se você procurar
203.159: aí, por exemplo, na Web Motors, um
204.599: abraço para meus amigos da Web Motors,
206.28: você acha modelos aí sendo zero km,
209.76: obviamente sendo vendidos com
211.599: descontinho de 10.000, 205.000. É isso,
215.519: Lucão. Por essa grana já dá para pegar
219.0: um híbrido plugin, só que chinês. Vamos
221.36: ver se tem um alarme aqui. Tem, tem um
222.76: alarme, só que é chinês.
225.64: Um híbrido plugin. Não, um híbrido. É. E
229.2: aí que tá o lance.
230.92: Vamos, filho. Vai fechar não.
233.48: Agora foi. E aqui tá o lance.
236.959: Esse aqui também é. Finalmente se
238.879: assustou. Entramos aqui no banco de trás
241.92: do Ford Territory. Temos encostinto de
246.04: três pontos, todos os airbags, o que é
247.92: muito bom. E, cara, um banco muito
249.56: confortável. Olha o espaço desse carro,
252.72: velho. Ó, espaço pra cabeça aqui
254.36: gigante. A gente tem um belíssimo tetão
256.359: solar. Aqui temos temos redinha. Em
259.32: breve você saberá o sapq para todos.
261.919: Luizinha e o banco é bem inclinado,
264.32: sabe? Ele é bem confortável mesmo.
266.04: Abrindo aqui dois porta-copos, tal, tudo
268.639: isso daí. Gostei da combinação desse
270.28: banquito.
272.36: Agora o que é aqui legal é você, ó,
275.56: deixou um tap aí no like pr ajudar o
277.52: canal. Você ajuda muito o canal. Seu
279.52: tapinha no like. Bate, bate gostoso aí
282.32: no like. Você me ajuda muito. O teto tá
284.039: bem azulado, bem bonitão, né? Antes de
286.68: falar do magnifico,
289.84: aqui, vamos falar do acabamento aqui que
291.72: é soft touch. Olha que loucura. Um toque
294.0: para descer, abre inteiro e um toque
296.36: para subir também. Tudo muito bem
299.28: forrado. Ó, couro aqui também. Só vai
301.479: ser plástico essa parte, que aqui uma
302.72: imitação de madeira. Tem até textura de
304.44: madeira. Uma luzinha para não ver um
305.96: louco de tuingo arrancar sua porta.
308.0: Borracha dupla. Olha o gatinho. Miau.
310.36: Miau.
312.44: Ele preferiu se retirar. Tá aí, ó.
314.56: Realmente um carro muito bonito. Isso,
316.96: isso tem que ser dito muito bem acabado
319.24: e muito espaçoso. Eu não sou da NASA,
324.6: mas eu vou mostrar o espaço agora pr
325.919: vocês. Que piada horrível. Que piada
328.039: horrível. Já segue nós lá no Instagram?
331.039: Segue nós lá. Digita lá assim, ó. Prof
333.4: Lucas Souza, até esqueci qual que era.
336.12: Digita lá que você me acha lá. Postei
337.68: vídeo primeiro desse carro lá. O
339.199: conteúdo assim, ó. Uma droga. Uma droga.
341.4: Legal que a gente tem luzinha aqui
343.12: também. Vamos falar do espaço. Ó, esse
345.199: banco tá regulado para mim cons muito
346.4: bem. Tô 1,83 m. Aconteceu que é. Tá aqui
348.319: a luzinha bem legal. Você consegue mudar
350.12: lá na central multimídia? Ó o espaço, ó.
352.56: Ó. Não, assim, ó.
356.919: CPAN é o maior espaço interno da
358.479: categoria.
360.039: Se não for um melhor, tá, tá assim entre
362.319: os dois ou três melhores. Eu não, o
365.0: espaço interno do carro é absurdo. Ó,
367.56: não tem túnel central, então dá para
368.96: três pessoas viajarem bem aqui. Duas
371.28: saidas diário para quem tá aqui atrás.
372.96: Só uma porte USB, tá? Os três adultos
376.039: aqui que saiam no soco. Realmente, cara,
378.08: é espaço de Ford Landalro aqui, olha.
381.68: Não, o carro realmente é muito espaçoso.
383.4: Esse banco aqui, ó, tá o máximo pra
385.199: frente possível. Olha como ele é lá na
387.52: frente. Já depois eu mostro. Olha o
390.039: espaço aqui, ó, com o banco mais pra
391.28: frente possível. Eu cruzo a perna,
393.479: velho. Olha aqui.
396.039: Não, realmente é um absurdo. O que é pr
398.479: elogiar, nós elogia. O que é pr
400.08: criticar, nós critica.
403.12: Consumo 8 e5 na cidade, 12 na estrada,
406.08: lembrando só na gasolina.
408.599: Milagres
410.16: não, não existem. Vamos lá pra frente.
412.16: Vem. Finalmente aqui no banco da
414.0: frenteira do Ford Teror.
418.879: Cara, que acabamento. Ó, isso aqui eles
421.4: podiam dar aula, hein? Ó, tudo soft
423.44: touch. Tu não encosta a mão num
425.319: plástico, tá? Não encosta. Aqui tem um
428.199: um uma borrachinha aqui pr você deixar
429.84: alguma coisa. A luzinha aqui também que
432.199: dá para você mudar, vai até a porta.
434.68: Porta-luvas aqui tem tamanho bom. Ficou
436.759: devendo uma luzinha aqui, né? Mas tá aí,
438.96: ó. Belíssimo acabamento, viu? E sim, se
441.72: você reparou a música, foi um eg. Foi um
444.879: est, sim. Eu gosto de ser pontora. O
446.68: banco é bem confortável. Ajustes
448.72: eletrônicos, tanto pro motorista quanto
450.56: pro passageiro. Tem ajuste de lombar que
452.039: é uma coisa que eu que tô tiozinho,
454.0: gosto bastante. Volante, por sua vez,
456.879: temos ajuste de altura e de
458.52: profundidade. Famosa regulagem kid. Eu
460.16: gosto de fazer seu kid, também gosto do
462.12: furadinho em couro. Temos aqui
464.039: assistente de permanência em faxa,
465.4: piloto automático adaptativo do melhor
466.879: tipo par e anda. Já vou mostrar para
468.319: vocês funcionando a tecla mais confusa
471.4: do mundo. Já mostro melhor para vocês.
473.84: Farol alto, limpador automático,
476.68: retrovisorcrômico,
478.24: tudo azulzinho, tá vendo? Bonito, né?
480.36: Cor aqui também, cor aqui também. Todos
482.52: os vídeos automáticos, um toque. O
484.36: retrovisor rebate eletronicamente, tem
486.879: alerta de ponto cego, tem repetidor de
489.52: seta, também tem o botãozinho aqui para
491.36: abrir o porta-malas aqui. É realmente um
493.919: carrinho bem completo. Central
495.759: multimídia tem Android Auto e Apple
497.28: CarPlay sem fio, porém,
500.84: cara, é muito simples e muito confusa.
504.36: Ó, vindo para cá, né, eu tenho acesso
506.44: aqui as principais funções, né?
508.919: Inclusive, vamos começar falando, por
510.84: exemplo, ó. Tô aqui mexendo no no num
513.159: bregen qualquer. Quero mexer no ar
515.039: condicionado. Ele até tem aqui função
516.68: alta e umas teclinhas táteis. Então, por
518.959: exemplo, a hora que eu clico, ó, ele até
521.719: sobe, aí ele sobe o menu, né? Que é uma
523.919: coisa bem de carro chinês que eu odeio
525.48: isso. Se já tem isso, né? Você já tem um
527.8: botãozinho, não precisava subir o menu e
529.56: aí realmente ã me atrapalha, né? Eu
532.76: consigo ligar a ventilação do banco. Tem
534.88: que ser por aqui, mas consigo ligar. Tem
536.88: o que? A bunda não faz falta tanto pro
538.72: motorista quanto para o passageiro. E
541.64: ela é um pouquinho confusa, né? Você vê
543.32: que, né? Eu quero mudar algumas coisas.
545.72: Então, configurações da carroceria,
548.399: luzes, vou ter que vir aqui, travas. E
551.0: ela e ela não é assim tão rápida também.
554.079: Mas o pior para mim é o seguinte. Se eu
557.32: quiser mudar os modos de condução, eu
559.64: tenho que estar aqui nessa tela. Por
561.959: exemplo, se eu estou no Android Auto, eu
564.72: não consigo. Por quê? Porque eu tem que
566.279: tá aqui qualquer tela que desde que não
568.64: seja Android Auto ou Apple CarPlay. E aí
570.399: eu faço assim e aí eu mudo. Ó lá, modo
574.88: esporte, modo serra ou colina, lembrando
578.839: que tração sofre inteira e modo eco. Tá
582.279: aí mexer a luminosidade tem que ser por
584.64: aqui também. Enfim, agora se eu tiver,
586.839: por exemplo, no Android Auto e Apple
588.2: CarPlay quiser fazer isso, que pena para
590.76: mim, porque, ó, não faz, não faz. Então,
594.36: preciso voltar pra home. Ainda bem que a
596.68: gente tem aqui alguns botõezinhos,
598.24: inclusive botãozinho da home. Aí eu
600.32: consigo voltar, né? Se eu já tiver aqui,
603.0: tiver sei lá, aqui fonte da juventude,
605.76: fizer assim, eu consigo, né? Aqui tem
607.92: aqui alguns atalhozinhos, tal, tal. Tá
610.519: aí, né? Mas é bem simplesinha mesmo.
613.24: Mais simples ainda. O painel de
614.399: instrumentos. Calma que eu já mostro
616.32: aqui. Um carregador por indução. Faltou
617.88: uma saidinha de ar para gelar ele. Tudo
619.959: couro aqui. Ali embaixo, ó. Duas
622.519: portinhas USB, uma C, uma normal. Tudo
625.56: emborrachado, tudo bonitão mesmo, viu? O
627.56: carro é muito bem acabado. Botãozinho de
629.519: volume que eu gosto bastante. Botãozinho
632.24: pro carro estacionar sozinho. Sim, ele
634.04: estaciona para você, que é sempre muito
635.959: útil. freio de mão eletrônico, função
637.92: auto hold, stop, start e desligar o
639.959: sensor de estacionamento. Hora que você
641.92: coloca na ré, temos câmera 360º, muito
645.36: útil, né? A gente tem essa essa rondana
648.8: aqui, ó. Se eu abro a porta e o carro
650.88: começa a andar, ela sozinho trava o
653.48: carro e coloca no P, né, pr te evitar
656.56: fazer alguma coisa. E tem a função L
658.76: aqui de lucão. Lucão, função low, é
662.16: claro, estou brincando. Dois
664.04: porta-copos. Eu gosto bastante que eles
665.92: ficam aqui escondidinhos, né? Você
667.399: consegue apertar aqui o botão tal, tal,
669.959: tal. A chave tá aqui, né? Nada demais.
673.56: Travado, destravar, abriu o porta-mala,
674.88: não tem função ligar a distância. Aqui
677.04: um bauzinho que a hora que você abre,
679.04: você tem acesso, consegue deslizar isso
681.16: daqui, né? Ficou faltando ser
682.36: refrigerado para você deixar sua
684.279: grosélia gelando, não é mesmo? Já aqui
687.279: em cima, espelhinho com luz, bem legal.
689.48: Porta óculos para você me usar Riban.
692.399: Nada. Optei o lugar errado. Nada de
696.12: Juliete. Num carro desse. Teto solar,
699.079: né? Você pode abrir aqui. Bem legal, bem
701.2: bacana. Dá um rolê com a gatinha num dia
703.2: de sol aqui com o vento batendo nos seus
705.639: cabelos, bem bonitão. Ou então você
708.72: fecha aqui. E sim, momento para donos de
712.839: Biodício chorar no banho. Temos redinha.
717.12: Redinha assim. Dono de Volver X30 também
719.48: pode chorar no banho, tá? Tem redinha,
721.24: tem redinha. Olha aí, ó. Er redinha azul
723.6: também esse carro aqui para quem quem é
725.76: colorado, hein? Não vai gostar.
728.68: As luizinhas aqui também de LED. O cinto
730.92: tem regulagem de altura. E vamos falar
732.92: aqui
734.959: vergonhoso painel de instrumentos. Por
737.44: que, Loucão? Bom, vamos lá.
740.36: Primeiro, velocímetro. Velocímetro
742.839: digital, temperatura do líquido de
744.16: refecimento, nível de combustível, conta
746.92: giros, né? Eu consigo mudar o painel de
749.839: instrumentos? Consigo, ó, se eu vi aqui
751.6: e mudar os modos de condução, então, por
753.639: exemplo, boto no modo esportivo, ó lá,
755.8: ele vai mudar, vai ficar, vai, vai ficar
757.8: um jeito que é pior, porque eu não vejo
759.76: direito a rotação, né? Enfim, fica nesse
762.199: jeito meio assim, né? Enfim, as
764.199: informações do meio eu já vou mostrar
765.6: para vocês. Modo normal, que é o que
768.079: estávamos antes, modo eco, que é o modo
770.199: normal de outra cor, serra colina,
774.279: que volta pro modo esporte, não consigo
776.12: entender porquê. E aqui o modo normal de
779.56: novo. Beleza, Lucão. Só isso. Só isso. E
783.32: aí é muito louco que se eu desligo o
785.279: carro no modo esportivo, o painel tá no
787.44: modo esportivo. Eu desligo o carro, a
788.959: hora que eu ligo de novo, o painel
790.6: continua no modo esportivo. Mas o carro
792.68: não vai entender. Vai entender. Agora
795.04: para mexer aqui no meio, que é a única
797.16: parte que eu consigo mexer, é esse
799.399: botão, que também é um botão de volume.
802.24: E agora, Lucão? Bom, você primeiro
804.24: aperta essa tecla, aí você vai ter uma
806.0: mensagem no painel, configurações de
808.44: controles ativo ou de volume ativo.
811.24: Controle ativo. Aí eu consigo mudar as
813.48: informações. É isso. Que loucura é essa,
816.68: velho? Que loucura é
821.12: que loucura. Ó, eu consigo pressionar o
823.04: botão para resetar. É isso. Não, não tem
826.44: mais muita coisa. É muito genérico esse
828.399: painel de instrumentos, mano. Vai
829.8: entender, né?
832.48: Meu Deus do céu. De qualquer maneira,
834.36: chega de falar. Vamos levar essa
835.839: máquina, dar um rolê e ver qual é que é.
838.279: E é isso aí, galera. Olha a gente a
841.199: bordo do Teror.
845.24: Olha só quem te viu, quem te vê,
848.92: Territor, que foi grande peada aqui do
854.279: canal na geração antiga, né? Por quê?
858.079: Porque ele era muito manco, né? É,
860.24: andava pouco, bebia muito, continua
863.04: bebendo, mas agora tá bem melhor de
865.36: andar, né? A suspensão
869.56: chinesa é um pouco mais molenga, né? Não
872.959: é tão molenga que nem outros carros
874.44: chineses,
876.04: como Song, por exemplo, que eu acho
877.68: muito molenga, mas sim, é molenga, cara.
882.16: Sinceramente,
883.88: se você tivesse um painel de
886.88: instrumentos, ã, vamos colocar assim,
889.6: olha, um Lifan aqui funcionando, hein?
892.0: Se você tivesse um painel de
893.16: instrumentos
895.16: menos pior, um da Ford, um comuninho,
898.44: tipo do do Bronco antes do facelift
903.12: e um p e e uma e uma central multimídia
905.8: decente, você nem ia falar que esse
907.92: carro é é chinês, ia falar francês. Olha
910.44: só que absurdo. Piloto automático
912.44: adaptativo, funciona bonitinho, freia,
914.92: acelera tal. Assistente permanece fa
917.44: ainda é ruinzinho, mas é isso. É um
919.72: carro muito confortável, muito espaçoso,
922.6: anda bem,
924.68: corre, melhor dizendo, não é um carro
926.519: pesado. Ó, o carro da frente saiu, só dá
928.759: um totó no acelerador, ele segue viagem.
930.24: Então ele funciona no anda e para, né,
932.279: do trânsito, enfim, tá aí. É um mega
935.279: carro. Não, não, não é, é isso. Eu acho
938.639: que se ele fosse mais barato, né, ainda
940.319: tem todo esse lance de que lá fora já
942.279: trocou tal, né, pô, 200 pila. Já que é
946.12: para comprar carro chinês, você pode
947.279: pegar um tigo oito, né? Já que é, né?
951.12: Ah, mas esse é um Ford, um chinês.
955.24: Eu acho que esse carro tinha que ser
956.16: mais barato, só isso, né? Nessa faixa de
959.16: preço do preço oficial, 215 paus,
962.8: você já pode pensar em pegar um H6 Rev,
965.639: que já é híbrido, que é a mesma coisa
967.72: que esse carro lá fora, já tá híbrido.
969.92: Se vem ou não pro Brasil, não sei, né?
972.56: Faz um ano que a Ford lançou esse carro
974.24: aqui, um pouco mais de um ano. Acho que
976.24: é muito cedo para mudar, mas se não muda
979.319: também não fica competitivo. Aí, aí é
982.079: uma faca de dois legumes, que nem diria
985.36: os mamonas assassinas. Vamos, vamos pra
987.24: estrada acelerar e ver como é que é.
988.44: Bora lá. Bora lá então. Ja
991.88: na estrada, Jaque não, Ford aqui na
996.04: estrada. Territory, não é o territory.
1000.639: Chega, chega, chega, chega, chega. Então
1002.079: vamos lá. É
1005.199: assim, ele é uma mais um sub urbano. Ele
1007.199: não tem tanta potência assim por causa
1008.72: do peso, né? Você vê que a gente nem
1010.44: troca de marcha tem, o que realmente é
1012.68: uma pena. Ah, loucão, mas quem que vai
1014.92: trocar marcha esportivamente?
1017.639: Não é só esportivamente, porque, por
1019.92: exemplo, você vai passar no alargamento,
1021.279: tudo bem que ele tem um modo L que
1022.639: talvez, talvez deva segurar ali a
1025.16: primeira marcha, mas é bom, né? você
1026.88: segurar na primeira, enfim, ó, pisei,
1029.88: ele vai eventualmente,
1032.679: eventualmente
1034.439: ele chega lá. É, é isso. Assistente
1037.799: permanência em faixa, ó, ó. Ele até que
1040.0: me devolve. Não é um assistente assim
1041.28: que vai me manter centralizado. Você vê
1043.319: que ele vai, né? Vai, vai fazendo um
1045.559: pinball assim. Rapaz, eu vou me ferrar
1047.799: na volta. Mas é isso, ó que eu falei, a
1050.2: suspensão
1051.84: é um pouquinho mais
1054.16: molenguinha, né, como todo o carro
1056.039: chinês.
1057.679: Exceção o H6 GT, só o GT, tá? Os outros
1060.96: não, os outros são molenga. É isso,
1063.4: mano. Os outros Hás da vida. Enfim. E
1070.16: é um carro meio genérico, cara. Nessa
1073.0: faixa de preço
1075.2: da onde ele vem tem melhores. É isso.
1078.32: Veículo isso. É particularmente rápido,
1081.919: não é particularmente empolgante, é
1083.36: confortável para caramba. Belo espaço
1085.919: interno e belo acabamento. Mas nesse
1089.12: preço será? Controle de tração,

In [ ]:
from googleapiclient.discovery import build
import os
from dotenv import load_dotenv
# Carrega as variáveis do arquivo .env para o ambiente do sistema
load_dotenv()

# Acessa a variável
api_key = os.getenv('YOUTUBE_API_KEY')
video_id = 'BmYsInLDmrI'

youtube = build('youtube', 'v3', developerKey=api_key)

# Chamada para buscar comentários
response = youtube.commentThreads().list(
    part='snippet',
    videoId=video_id,
    maxResults=100,  # Máximo de 100 por requisição
    textFormat='plainText'
    order='relevance'
).execute()

response['items'][0]
for item in response['items']:
    comentario = item['snippet']['topLevelComment']['snippet']['textDisplay']
    like_count = item['snippet']['topLevelComment']['snippet']['likeCount']
    rep_total = item['snippet']['totalReplyCount']
    resp = item['replies']
    autor = item['snippet']['topLevelComment']['snippet']['authorDisplayName']
    print(f"{autor}: {comentario}")

{'kind': 'youtube#commentThread',
 'etag': 'ktprSd2lJNiWDOOB5_QSKnatQvg',
 'id': 'UgxQDmlacTl-O0lJZYF4AaABAg',
 'snippet': {'channelId': 'UCMk1wBIsHmalYeE16GkD6bg',
  'videoId': 'BmYsInLDmrI',
  'topLevelComment': {'kind': 'youtube#comment',
   'etag': 'ud37k45b5Cjzd2m_CRdl8Ysgo_s',
   'id': 'UgxQDmlacTl-O0lJZYF4AaABAg',
   'snippet': {'channelId': 'UCMk1wBIsHmalYeE16GkD6bg',
    'videoId': 'BmYsInLDmrI',
    'textDisplay': 'Tenho um 2025. Carro sensacional. Pelo valor e por tudo que oferece, não vejo uma opção confiável que seja melhor.',
    'textOriginal': 'Tenho um 2025. Carro sensacional. Pelo valor e por tudo que oferece, não vejo uma opção confiável que seja melhor.',
    'authorDisplayName': '@viniciusvasconcelos8398',
    'authorProfileImageUrl': 'https://yt3.ggpht.com/ytc/AIdro_kvPzSWHTfu9lxV3HpVDEHbJAkPRxjo2fEfeXTmGg=s48-c-k-c0x00ffffff-no-rj',
    'authorChannelUrl': 'http://www.youtube.com/@viniciusvasconcelos8398',
    'authorChannelId': {'value': 'UC9EaWYlDUAethDuC2F1bPHA'},
    'canRate': True,
    'viewerRating': 'none',
    'likeCount': 0,
    'publishedAt': '2026-03-28T11:00:11Z',
    'updatedAt': '2026-03-28T11:00:11Z'}},
  'canReply': True,
  'totalReplyCount': 0,
  'isPublic': True}}

In [ ]:
from googleapiclient.discovery import build
import os
from dotenv import load_dotenv

load_dotenv()
youtube = build('youtube', 'v3', developerKey=os.getenv('YOUTUBE_API_KEY'))

def buscar_review_carro(marca, modelo, tipo,dt_ini,dt_fim):
    # Monta uma query de busca otimizada
    # Usar "review" ou "avaliação" ajuda a filtrar conteúdos opinativos
    query = f"review avaliação {marca} {modelo} {tipo}"
    
    request = youtube.search().list(
        q=query,
        part='snippet',
        type='video',
        maxResults=5,
        order='relevance',         # Prioriza os mais relevantes
        relevanceLanguage='pt',    # Foca em português   # Filtra por vídeos em HD (melhor UX para reviews)
        publishedAfter=dt_ini,
        publishedBefore=dt_fim
    )
    
    return request.execute()

from datetime import datetime, timedelta, timezone

def definir_periodo_busca(meses_atras=6):
    # Data atual em UTC no formato RFC 3339
    agora = datetime.now(timezone.utc)
    
    # Data limite (agora menos X meses)
    data_inicio = agora - timedelta(days=meses_atras * 30)
    
    # Formatação para RFC 3339 (ex: 2026-04-21T12:00:00Z)
    # O 'Z' indica UTC, que é o padrão exigido pelo YouTube
    published_after = data_inicio.strftime('%Y-%m-%dT%H:%M:%SZ')
    published_before = agora.strftime('%Y-%m-%dT%H:%M:%SZ')
    
    return published_after, published_before

# Obter as datas
inicio, fim = definir_periodo_busca(6)

# Exemplo de uso dinâmico:
resultado = buscar_review_carro("Toyota", "Corolla", "sedan")

for item in resultado['items']:
    video_id = item['id']['videoId']
    titulo = item['snippet']['title']
    descricao = item['snippet']['description']
    canal = item['snippet']['channelTitle']
    data_publicacao = item['snippet']['publishedAt']

    # Acessando a miniatura de alta qualidade
    thumbnail_url = item['snippet']['thumbnails']['high']['url']

    # Montando a URL do vídeo
    url_video = f"https://www.youtube.com/watch?v={video_id}"

    print(f"Título: {titulo}")
    print(f"Canal: {canal}")
    print(f"Data: {data_publicacao}")
    print(f"URL da Thumbnail: {thumbnail_url}")
    print(f"Link: {url_video}")

    print("=" * 80)

Título: O MELHOR COROLLA DE TODOS OS TEMPOS! Avaliação Toyota Corolla ALTIS 2014
Canal: Carro Chefe
Data: 2026-01-16T20:55:14Z
URL da Thumbnail: https://i.ytimg.com/vi/t7JqSehIbGE/hqdefault.jpg
Link: https://www.youtube.com/watch?v=t7JqSehIbGE
================================================================================
Título: Avaliação Toyota Corolla SEG 2005 Automático - o melhor Corolla já lançado!
Canal: Carro Chefe
Data: 2019-04-25T21:57:43Z
URL da Thumbnail: https://i.ytimg.com/vi/srvo2JouVno/hqdefault.jpg
Link: https://www.youtube.com/watch?v=srvo2JouVno
================================================================================
Título: Avaliação Toyota Corolla Hibrido 2025 - IMPRESSIONA MUITO PELO PREÇO mas não de maneira positiva
Canal: Carro Chefe
Data: 2025-05-23T20:56:04Z
URL da Thumbnail: https://i.ytimg.com/vi/r_FiBY59nf0/hqdefault.jpg
Link: https://www.youtube.com/watch?v=r_FiBY59nf0
================================================================================
Título: Avaliação Toyota Corolla 2003 - O MELHOR COROLLA JÁ FEITO! DESCCUBRA O SEGREDO PARA COMPRAR UM BOM
Canal: Carro Chefe
Data: 2025-02-12T20:56:55Z
URL da Thumbnail: https://i.ytimg.com/vi/JICFgcIv4TQ/hqdefault.jpg
Link: https://www.youtube.com/watch?v=JICFgcIv4TQ
================================================================================
Título: Avaliação NOVO Corolla Híbrido 2024 - MUITO ECONOMICO, MUITO CONFIÁVEL E POUCA COISA POR MUITA GRANA
Canal: Carro Chefe
Data: 2024-02-12T20:55:18Z
URL da Thumbnail: https://i.ytimg.com/vi/GGyrnxu_PGU/hqdefault.jpg
Link: https://www.youtube.com/watch?v=GGyrnxu_PGU
================================================================================

In [20]:
from googleapiclient.discovery import build
import os
from dotenv import load_dotenv

load_dotenv()
youtube = build('youtube', 'v3', developerKey=os.getenv('YOUTUBE_API_KEY'))

stats_response = youtube.videos().list(
            part='statistics',
            id='bAHpYCRMkTM'
        ).execute()

print(stats_response)

{'kind': 'youtube#videoListResponse', 'etag': '2WL7MYhvmzIKI3KG26yGj4m6j2I', 'items': [{'kind': 'youtube#video', 'etag': 'N-WZBXFUWirgXuvD6eXVUf2E72g', 'id': 'bAHpYCRMkTM', 'statistics': {'viewCount': '35595', 'likeCount': '3107', 'favoriteCount': '0', 'commentCount': '25'}}], 'pageInfo': {'totalResults': 1, 'resultsPerPage': 1}}

In [31]:

def definir_periodo_busca(meses_atras=6):
    # Data atual em UTC no formato RFC 3339
    agora = datetime.now(timezone.utc)
    
    # Data limite (agora menos X meses)
    data_inicio = agora - timedelta(days=meses_atras * 30)
    
    # Formatação para RFC 3339 (ex: 2026-04-21T12:00:00Z)
    # O 'Z' indica UTC, que é o padrão exigido pelo YouTube
    published_after = data_inicio.strftime('%Y-%m-%dT%H:%M:%SZ')
    published_before = agora.strftime('%Y-%m-%dT%H:%M:%SZ')
    
    return published_after, published_before

# Obter as datas
dt_ini, dt_fim = definir_periodo_busca(6)

order = 'relevance'  # ou 'date' para os mais recentes





query = f"review avaliação Ford Territory 2026"
search_response = youtube.search().list(
        q=query, type='video', maxResults=1 , part='snippet',     # Prioriza os mais relevantes
        relevanceLanguage='pt',
        publishedAfter=dt_ini,
        publishedBefore=dt_fim
    ).execute()

print(search_response)

{'kind': 'youtube#searchListResponse', 'etag': '6xNB7SCaKmUK-5NXNjJYPFc6RtA', 'nextPageToken': 'CAEQAA', 'regionCode': 'BR', 'pageInfo': {'totalResults': 1939, 'resultsPerPage': 1}, 'items': [{'kind': 'youtube#searchResult', 'etag': 'Dcu48ME1cwqJa30gQsWN3m1WaWM', 'id': {'kind': 'youtube#video', 'videoId': 'Hsb-Y8OqXaQ'}, 'snippet': {'publishedAt': '2026-04-02T23:09:38Z', 'channelId': 'UCV7ZpRaSA8EsuCNT3ouygWQ', 'title': 'Ford Territory 2026 - Super espaçoso e confortável mas NÃO É FLEX', 'description': 'Confira os links dos parceiros do Xenão com descontos e vantagens exclusivas pra você: Camisetas PaddockBR - Cupom ...', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/Hsb-Y8OqXaQ/default.jpg', 'width': 120, 'height': 90}, 'medium': {'url': 'https://i.ytimg.com/vi/Hsb-Y8OqXaQ/mqdefault.jpg', 'width': 320, 'height': 180}, 'high': {'url': 'https://i.ytimg.com/vi/Hsb-Y8OqXaQ/hqdefault.jpg', 'width': 480, 'height': 360}}, 'channelTitle': 'Carros do Xenão', 'liveBroadcastContent': 'none', 'publishTime': '2026-04-02T23:09:38Z'}}]}

In [ ]:
from googleapiclient.discovery import build
import os
from dotenv import load_dotenv
from datetime import datetime, timedelta, timezone

load_dotenv()
youtube = build('youtube', 'v3', developerKey=os.getenv('YOUTUBE_API_KEY'))


def definir_periodo_busca(meses_atras=6):
    # Data atual em UTC no formato RFC 3339
    agora = datetime.now(timezone.utc)
    
    # Data limite (agora menos X meses)
    data_inicio = agora - timedelta(days=meses_atras * 30)
    
    # Formatação para RFC 3339 (ex: 2026-04-21T12:00:00Z)
    # O 'Z' indica UTC, que é o padrão exigido pelo YouTube
    published_after = data_inicio.strftime('%Y-%m-%dT%H:%M:%SZ')
    published_before = agora.strftime('%Y-%m-%dT%H:%M:%SZ')
    
    return published_after, published_before

# Obter as datas
dt_ini, dt_fim = definir_periodo_busca(6)

order = 'relevance'  # ou 'date' para os mais recentes

def buscar_info_video(marca, modelo,ano,dt_ini,dt_fim,order='relevance'):
    query = f"review avaliação {marca} {modelo} {ano}"
    print(f"Buscando vídeos com a query: {query} entre {dt_ini} e {dt_fim} ordenados por {order}")
    # 1. Busca os vídeos
    search_response = youtube.search().list(
        q=query, part='snippet', type='video', maxResults=15 , order=order,         # Prioriza os mais relevantes
        relevanceLanguage='pt',
        publishedAfter=dt_ini,
        publishedBefore=dt_fim
    ).execute()

    resultados_finais = [] 

    for item in search_response['items']:
        video_id = item['id']['videoId']
        
        # 2. Busca estatísticas (incluindo views) usando o ID
        stats_response = youtube.videos().list(
            part='statistics',
            id=video_id
        ).execute()
        
        views = stats_response['items'][0]['statistics'].get('viewCount', '0')
        likes = stats_response['items'][0]['statistics'].get('likeCount', '0')
        favorites = stats_response['items'][0]['statistics'].get('favoriteCount', '0')
        comments = stats_response['items'][0]['statistics'].get('commentCount', '0')
        # 3. Organiza os dados
        video_info = {
            'titulo': item['snippet']['title'],
            'data': item['snippet']['publishedAt'],
            'link': f"https://www.youtube.com/watch?v={video_id}",
            'canal': item['snippet']['channelTitle'],
            'views': views,
            'likes': likes,
            'favorites': favorites,
            'comments': comments
        }
        resultados_finais.append(video_info)
        
    return resultados_finais

# Exemplo de execução
dados = buscar_info_video(marca="Ford", modelo="Territory", ano=2026, dt_ini=dt_ini, dt_fim=dt_fim, order=order)
for v in dados:
    print(f"Título: {v['titulo']}\nData: {v['data']}\nViews: {v['views']}\nLikes: {v['likes']}\nFavorites: {v['favorites']}\nComments: {v['comments']}\nLink: {v['link']}\nCanal: {v['canal']}\n")

Buscando vídeos com a query: review avaliação Ford Territory 2026 entre 2025-10-23T04:05:27Z e 2026-04-21T04:05:27Z ordenados por relevance
Título: Ford Territory 2026 - Super espaçoso e confortável mas NÃO É FLEX
Data: 2026-04-02T23:09:38Z
Views: 34816
Likes: 2419
Favorites: 0
Comments: 108
Link: https://www.youtube.com/watch?v=Hsb-Y8OqXaQ
Canal: Carros do Xenão

Título: AVALIAÇÃO NOVO FORD TERRITORY 2026 EM DETALHES
Data: 2026-04-04T17:16:52Z
Views: 3631
Likes: 218
Favorites: 0
Comments: 17
Link: https://www.youtube.com/watch?v=52hS7nvBKaE
Canal: Car Analysis | Rafael Amaral

Título: NOVO FORD TERRITORY 2026 Teste na vida real! Melhor que Renault BOREAL e TIGGO 8 PRO 2026?
Data: 2025-10-25T21:15:00Z
Views: 13618
Likes: 468
Favorites: 0
Comments: 47
Link: https://www.youtube.com/watch?v=3nKUA-FSM14
Canal: MyCars

Título: TEST DRIVE NOVO FORD TERRITORY TITANIUM 2026
Data: 2025-11-03T21:00:22Z
Views: 2307
Likes: 102
Favorites: 0
Comments: 6
Link: https://www.youtube.com/watch?v=O_I7KNX1N5k
Canal: NO12

Título: Ford Territory 2026 POV – Test Drive Completo + Minha Opinião Ao Volante, Vale a Pena?
Data: 2025-11-21T22:00:49Z
Views: 1025
Likes: 39
Favorites: 0
Comments: 8
Link: https://www.youtube.com/watch?v=b1lHnbg11Ns
Canal: Warlinho Autostage

Título: Ford Territory é BOM ou RUIM? Pontos fortes e fracos. Esse SUV Vale a Pena? Consumo, problema, teste
Data: 2026-02-13T21:00:17Z
Views: 20229
Likes: 1414
Favorites: 0
Comments: 105
Link: https://www.youtube.com/watch?v=JLdgQqZHRYE
Canal: Opinião Sincera

Título: FORD TERRITORY 2026 EM DETALHES E PREÇO
Data: 2025-12-21T15:00:33Z
Views: 17109
Likes: 864
Favorites: 0
Comments: 24
Link: https://www.youtube.com/watch?v=FkiTQf4Sg4A
Canal: Top Motor BR

Título: NOVO FORD TERRITORY 2026 PELA NOITE VAI TE SURPREENDER!
Data: 2026-04-05T13:09:44Z
Views: 2453
Likes: 193
Favorites: 0
Comments: 11
Link: https://www.youtube.com/watch?v=YCzMAlGROpA
Canal: Car Analysis | Rafael Amaral

Título: NOVO FORD TERRITORY 2026 Tem Desconto! Mas e o sistema híbrido quando chega? Melhor que BOREAL?
Data: 2026-01-27T21:01:11Z
Views: 15535
Likes: 898
Favorites: 0
Comments: 77
Link: https://www.youtube.com/watch?v=3xgUjZl0QjA
Canal: MyCars

Título: Teste NOVO FORD TERRITORY 2026 - Vale MESMO a pena comprar o SUV? Tira-Teima completo no USO DIÁRIO
Data: 2025-11-12T21:00:25Z
Views: 3162
Likes: 170
Favorites: 0
Comments: 19
Link: https://www.youtube.com/watch?v=BLE65CTY1vw
Canal: Atlas Auto

Título: Ford Territory 2026 Review black
Data: 2025-11-29T06:00:37Z
Views: 133778
Likes: 1559
Favorites: 0
Comments: 12
Link: https://www.youtube.com/watch?v=_Ow4TiZhX44
Canal: AutoShow TV

Título: New 2026 Ford Territory Black - 1.5L Best Premium Family SUV | $42900
Data: 2025-12-01T11:00:16Z
Views: 7960
Likes: 87
Favorites: 0
Comments: 0
Link: https://www.youtube.com/watch?v=eSLPCtRMAL4
Canal: AutoShow TV

Título: Ford Territory Titanium X 2026 | មានការផ្លាស់ប្តូរយ៉ាងច្រើន
Data: 2025-11-15T12:00:15Z
Views: 1326
Likes: 13
Favorites: 0
Comments: 8
Link: https://www.youtube.com/watch?v=7gTUvlnXdUI
Canal: Chhaysreng Sok

Título: NOVO TERRITORY 2026 É ÓTIMO MAS NINGUÉM LEMBRA! MOTOR HÍBRIDO E TRAÇÃO INTEGRAL AJUDARIA NAS VENDAS?
Data: 2026-01-04T22:45:07Z
Views: 8419
Likes: 376
Favorites: 0
Comments: 31
Link: https://www.youtube.com/watch?v=stqADpo5nwI
Canal: Fast Car View

Título: Ford Territory 2026 - No tiene NADA que Ver con lo que ESPERABA | Reseña
Data: 2026-03-18T23:05:00Z
Views: 24214
Likes: 0
Favorites: 0
Comments: 67
Link: https://www.youtube.com/watch?v=kgtN9_OlIA0
Canal: CarshopGaraje

In [32]:
import os
from dotenv import load_dotenv
from datetime import datetime, timedelta, timezone
from googleapiclient.discovery import build

# Configuração da API
load_dotenv()
youtube = build('youtube', 'v3', developerKey=os.getenv('YOUTUBE_API_KEY'))

def definir_periodo_busca(meses_atras=6):
    agora = datetime.now(timezone.utc)
    data_inicio = agora - timedelta(days=meses_atras * 30)
    return data_inicio.strftime('%Y-%m-%dT%H:%M:%SZ'), agora.strftime('%Y-%m-%dT%H:%M:%SZ')

def obter_dados_canal(channel_id):
    """Busca estatísticas detalhadas do canal."""
    response = youtube.channels().list(
        part='snippet,statistics',
        id=channel_id
    ).execute()
    
    if 'items' in response and response['items']:
        canal = response['items'][0]
        stats = canal['statistics']
        return {
            'nome': canal['snippet']['title'],
            'inscritos': stats.get('subscriberCount', '0'),
            'total_views_canal': stats.get('viewCount', '0'),
            'data_criacao': canal['snippet']['publishedAt']
        }
    return None

def buscar_info_video(marca, modelo, ano, dt_ini, dt_fim, order='relevance'):
    query = f"review avaliação {marca} {modelo} {ano}"
    print(f"--- Iniciando busca: {query} ---")
    
    # 1. Busca os vídeos
    search_response = youtube.search().list(
        q=query, part='snippet', type='video', maxResults=5, 
        order=order, relevanceLanguage='pt',
        publishedAfter=dt_ini, publishedBefore=dt_fim
    ).execute()

    resultados_finais = [] 

    for item in search_response['items']:
        video_id = item['id']['videoId']
        channel_id = item['snippet']['channelId']
        
        # 2. Busca estatísticas do vídeo
        stats_response = youtube.videos().list(
            part='statistics',
            id=video_id
        ).execute()
        
        stats = stats_response['items'][0]['statistics']
        
        # 3. Busca dados do canal
        canal_info = obter_dados_canal(channel_id)
        
        # 4. Organiza os dados
        video_info = {
            'titulo': item['snippet']['title'],
            'data': item['snippet']['publishedAt'],
            'link': f"https://www.youtube.com/watch?v={video_id}",
            'canal': item['snippet']['channelTitle'],
            'views': stats.get('viewCount', '0'),
            'likes': stats.get('likeCount', '0'),
            'favorites': stats.get('favoriteCount', '0'),
            'comments': stats.get('commentCount', '0'),
            'canal_inscritos': canal_info.get('inscritos') if canal_info else 'N/A'
        }
        resultados_finais.append(video_info)
        
    return resultados_finais

# --- Execução ---
dt_ini, dt_fim = definir_periodo_busca(6)
dados = buscar_info_video(marca="Ford", modelo="Territory", ano=2026, dt_ini=dt_ini, dt_fim=dt_fim)

for v in dados:
    print(f"Título: {v['titulo']}")
    print(f"Data: {v['data']} | Views: {v['views']} | Likes: {v['likes']}")
    print(f"Canal: {v['canal']} | Inscritos: {v['canal_inscritos']}")
    print(f"Link: {v['link']}\n" + "-"*50)

--- Iniciando busca: review avaliação Ford Territory 2026 ---
Título: Ford Territory 2026 - Super espaçoso e confortável mas NÃO É FLEX
Data: 2026-04-02T23:09:38Z | Views: 34818 | Likes: 2419
Canal: Carros do Xenão | Inscritos: 1170000
Link: https://www.youtube.com/watch?v=Hsb-Y8OqXaQ
--------------------------------------------------
Título: AVALIAÇÃO NOVO FORD TERRITORY 2026 EM DETALHES
Data: 2026-04-04T17:16:52Z | Views: 3631 | Likes: 218
Canal: Car Analysis | Rafael Amaral | Inscritos: 206000
Link: https://www.youtube.com/watch?v=52hS7nvBKaE
--------------------------------------------------
Título: NOVO FORD TERRITORY 2026 Teste na vida real! Melhor que Renault BOREAL e TIGGO 8 PRO 2026?
Data: 2025-10-25T21:15:00Z | Views: 13618 | Likes: 468
Canal: MyCars | Inscritos: 130000
Link: https://www.youtube.com/watch?v=3nKUA-FSM14
--------------------------------------------------
Título: TEST DRIVE NOVO FORD TERRITORY TITANIUM 2026
Data: 2025-11-03T21:00:22Z | Views: 2307 | Likes: 102
Canal: NO12 | Inscritos: 7690
Link: https://www.youtube.com/watch?v=O_I7KNX1N5k
--------------------------------------------------
Título: Ford Territory 2026 POV – Test Drive Completo + Minha Opinião Ao Volante, Vale a Pena?
Data: 2025-11-21T22:00:49Z | Views: 1025 | Likes: 39
Canal: Warlinho Autostage | Inscritos: 2110
Link: https://www.youtube.com/watch?v=b1lHnbg11Ns
--------------------------------------------------

In [35]:
import os
import csv
from dotenv import load_dotenv
from datetime import datetime, timedelta, timezone
from googleapiclient.discovery import build

# Configuração inicial
load_dotenv()
API_KEY = os.getenv('YOUTUBE_API_KEY')

if not API_KEY:
    raise ValueError("A chave YOUTUBE_API_KEY não foi encontrada no arquivo .env")

youtube = build('youtube', 'v3', developerKey=API_KEY)

def definir_periodo_busca(meses_atras):
    """Retorna as datas de início e fim no formato RFC 3339 exigido pelo YouTube."""
    agora = datetime.now(timezone.utc)
    data_inicio = agora - timedelta(days=meses_atras * 30)
    return data_inicio.strftime('%Y-%m-%dT%H:%M:%SZ'), agora.strftime('%Y-%m-%dT%H:%M:%SZ')

def executar_pipeline_busca(marca, modelo, ano, meses_atras=6, max_resultados=15, order='relevance', arquivo_saida='resultados.csv'):
    """
    Função principal que gerencia a extração otimizada (Batching) e exportação para CSV.
    Todos os parâmetros de busca são dinâmicos e configuráveis na chamada.
    """
    dt_ini, dt_fim = definir_periodo_busca(meses_atras)
    query = f"review avaliação {marca} {modelo} {ano}"
    print(f"Buscando: '{query}' | Período: {dt_ini} até {dt_fim} | Max: {max_resultados}")
    
    # ---------------------------------------------------------
    # PASSO 1: Buscar os Vídeos (1 Requisição)
    # ---------------------------------------------------------
    search_response = youtube.search().list(
        q=query, part='snippet', type='video', maxResults=max_resultados, 
        order=order, relevanceLanguage='pt',
        publishedAfter=dt_ini, publishedBefore=dt_fim
    ).execute()

    itens_encontrados = search_response.get('items', [])
    if not itens_encontrados:
        print("Nenhum vídeo encontrado com esses parâmetros.")
        return

    # Extrai listas separadas de IDs para fazer as requisições em lote
    video_ids = [item['id']['videoId'] for item in itens_encontrados]
    # Usa 'set' para remover IDs de canais duplicados (caso um canal tenha 2 vídeos na lista)
    channel_ids = list(set([item['snippet']['channelId'] for item in itens_encontrados]))

    # ---------------------------------------------------------
    # PASSO 2: Buscar Estatísticas dos Vídeos em Lote (1 Requisição)
    # ---------------------------------------------------------
    # Passamos todos os IDs de uma vez separados por vírgula
    video_stats_response = youtube.videos().list(
        part='statistics', id=','.join(video_ids)
    ).execute()
    
    # Cria um dicionário de acesso rápido: { 'id_do_video': {estatisticas} }
    video_stats_map = {v['id']: v['statistics'] for v in video_stats_response.get('items', [])}

    # ---------------------------------------------------------
    # PASSO 3: Buscar Estatísticas dos Canais em Lote (1 Requisição)
    # ---------------------------------------------------------
    channel_stats_response = youtube.channels().list(
        part='statistics', id=','.join(channel_ids)
    ).execute()
    
    # Dicionário de acesso rápido: { 'id_do_canal': {estatisticas} }
    channel_stats_map = {c['id']: c['statistics'] for c in channel_stats_response.get('items', [])}

    # ---------------------------------------------------------
    # PASSO 4: Mesclar Dados e Preparar Base
    # ---------------------------------------------------------
    resultados_finais = []
    
    for item in itens_encontrados:
        v_id = item['id']['videoId']
        c_id = item['snippet']['channelId']
        
        # Resgata os dados dos mapas criados acima (ou dicionários vazios se houver falha)
        v_stats = video_stats_map.get(v_id, {})
        c_stats = channel_stats_map.get(c_id, {})
        
        video_info = {
            'video_id': v_id,
            'titulo': item['snippet']['title'],
            'data_publicacao': item['snippet']['publishedAt'],
            'canal_nome': item['snippet']['channelTitle'],
            'canal_id': c_id,
            'video_views': v_stats.get('viewCount', '0'),
            'video_likes': v_stats.get('likeCount', '0'),
            'video_comments': v_stats.get('commentCount', '0'),
            'canal_inscritos': c_stats.get('subscriberCount', '0'),
            'canal_total_views': c_stats.get('viewCount', '0'),
            'link_url': f"https://www.youtube.com/watch?v={v_id}"
        }
        resultados_finais.append(video_info)

    # ---------------------------------------------------------
    # PASSO 5: Salvar em CSV
    # ---------------------------------------------------------
    salvar_em_csv(resultados_finais, arquivo_saida)

def salvar_em_csv(dados, nome_arquivo):
    """Recebe a lista de dicionários e exporta para CSV."""
    if not dados:
        return
    
    # As chaves do primeiro dicionário serão os cabeçalhos do CSV
    cabecalhos = dados[0].keys()
    with open(nome_arquivo, mode='w', newline='', encoding='utf-8') as arquivo:
        writer = csv.DictWriter(arquivo, fieldnames=cabecalhos, delimiter=';')
        
        writer.writeheader()
        for linha in dados:
            writer.writerow(linha)
            
    print(f"\nSucesso! {len(dados)} registros salvos no arquivo '{nome_arquivo}'.")


# =========================================================
# EXECUÇÃO DO PIPELINE
# =========================================================
if __name__ == '__main__':
    # Você pode chamar essa função passando os dados do carro desejado
    executar_pipeline_busca(
        marca="Ford",
        modelo="Territory",
        ano=2026,
        meses_atras=10,          # Busca no último 1 ano
        max_resultados=20,       # Máximo de vídeos retornados (Limite: 50 por vez)
        order='viewCount',       # Traz os mais vistos primeiro (ou 'relevance', 'date')
        arquivo_saida='base_ford_territory.csv'
    )

Buscando: 'review avaliação Ford Territory 2026' | Período: 2025-06-25T04:40:37Z até 2026-04-21T04:40:37Z | Max: 20

Sucesso! 20 registros salvos no arquivo 'base_ford_territory.csv'.

In [36]:
import pandas as pd

df = pd.read_csv('base_ford_territory.csv', delimiter=';')
print(df.head())

      video_id                                             titulo  \
0  BkFNJYONHTM  A REVIRAVOLTA DA RENAULT! ATROPELOU COMPASS E ...
1  w9p5i5NP0fA                     New CHERY Tiggo 8 2026! Review
2  UQm_Awc4sLU  FORD TERRITORY 2025 (Titanium) - Test - Matías...
3  GDNc13R1YA4                      La Ford Territory Es Distinta
4  QDLRS1hiMcE  2026 Ford Territory Review UAE | Ford Territor...

        data_publicacao     canal_nome                  canal_id  video_views  \
0  2025-11-06T19:00:22Z    Carro Chefe  UCMk1wBIsHmalYeE16GkD6bg       436191
1  2025-10-16T00:01:13Z      NewCar TV  UCvD1NoWY8E0egM2uaUKcQTw       679543
2  2025-08-31T23:12:13Z   MatiasAntico  UCd61IERUuGODiG08h3_30JA       362880
3  2025-09-27T19:00:23Z  Lucas Abriata  UCOypnH-5DDOh1WXHJxm_t1A       298903
4  2025-11-07T13:42:44Z     OTO Drive   UCt-TQyVs66iD0OifSIpnWDQ       297677

   video_likes  video_comments  canal_inscritos  canal_total_views  \
0        31986            1317          1680000          537071690
1         8033             227            34900           30199721
2         5424             553           697000          258029870
3        12603             762           369000           55738085
4          500              43          1080000            6248989

                                      link_url
0  https://www.youtube.com/watch?v=BkFNJYONHTM
1  https://www.youtube.com/watch?v=w9p5i5NP0fA
2  https://www.youtube.com/watch?v=UQm_Awc4sLU
3  https://www.youtube.com/watch?v=GDNc13R1YA4
4  https://www.youtube.com/watch?v=QDLRS1hiMcE

In [37]:
df

,video_id,titulo,data_publicacao,canal_nome,canal_id,video_views,video_likes,video_comments,canal_inscritos,canal_total_views,link_url
0,BkFNJYONHTM,A REVIRAVOLTA DA RENAULT! ATROPELOU COMPASS E ...,2025-11-06T19:00:22Z,Carro Chefe,UCMk1wBIsHmalYeE16GkD6bg,436191,31986,1317,1680000,537071690,https://www.youtube.com/watch?v=BkFNJYONHTM
1,w9p5i5NP0fA,New CHERY Tiggo 8 2026! Review,2025-10-16T00:01:13Z,NewCar TV,UCvD1NoWY8E0egM2uaUKcQTw,679543,8033,227,34900,30199721,https://www.youtube.com/watch?v=w9p5i5NP0fA
2,UQm_Awc4sLU,FORD TERRITORY 2025 (Titanium) - Test - Matías...,2025-08-31T23:12:13Z,MatiasAntico,UCd61IERUuGODiG08h3_30JA,362880,5424,553,697000,258029870,https://www.youtube.com/watch?v=UQm_Awc4sLU
3,GDNc13R1YA4,La Ford Territory Es Distinta,2025-09-27T19:00:23Z,Lucas Abriata,UCOypnH-5DDOh1WXHJxm_t1A,298903,12603,762,369000,55738085,https://www.youtube.com/watch?v=GDNc13R1YA4
4,QDLRS1hiMcE,2026 Ford Territory Review UAE | Ford Territor...,2025-11-07T13:42:44Z,OTO Drive,UCt-TQyVs66iD0OifSIpnWDQ,297677,500,43,1080000,6248989,https://www.youtube.com/watch?v=QDLRS1hiMcE
5,9v9iSnikNOw,Jetour T2 Review - The Best Value Adventure SU...,2025-12-17T13:00:21Z,Cars.co.za,UCB-mfYAd3oJLEkoMxjRAxbg,251671,2224,218,547000,196857864,https://www.youtube.com/watch?v=9v9iSnikNOw
6,0CzJO5FVnDE,Novo Renault BOREAL: Melhor SUV do Brasil? Det...,2025-11-06T19:00:01Z,Opinião Sincera,UCc0cU92Tf7rvd2gr-CpVO4Q,240880,10349,505,2150000,614129208,https://www.youtube.com/watch?v=0CzJO5FVnDE
7,y4_h7C-SBeY,Jetour T1 2026 Review,2025-07-30T22:01:09Z,AutoShow TV,UCVJdpj3jzdyq7QweTcUK9rg,377186,5814,24,458000,290931312,https://www.youtube.com/watch?v=y4_h7C-SBeY
8,MgFEBIYEO5I,Jetour T1 2026 Review Black Edition,2025-07-30T00:00:33Z,AutoShow TV,UCVJdpj3jzdyq7QweTcUK9rg,492047,4397,30,458000,290931312,https://www.youtube.com/watch?v=MgFEBIYEO5I
9,K5lvKm1H7kM,New CHERY Tiggo 9 2026! Review,2025-10-18T22:00:31Z,NewCar TV,UCvD1NoWY8E0egM2uaUKcQTw,414604,3071,26,34900,30199721,https://www.youtube.com/watch?v=K5lvKm1H7kM
10,XRYeckv9zk8,Jetour Dashing ECO 2026 Review,2025-07-30T02:00:33Z,AutoShow TV,UCVJdpj3jzdyq7QweTcUK9rg,395651,5265,32,458000,290931312,https://www.youtube.com/watch?v=XRYeckv9zk8
11,EXvSxIgahs4,TIGGO 8 PRO 2026 NOVO PREÇO! #cherrytigo8 #tig...,2025-09-15T14:30:09Z,MyCars,UCLFbmb6wLvCH42tVggh0KAA,290961,10652,272,130000,33043273,https://www.youtube.com/watch?v=EXvSxIgahs4
12,1jR49TNiKxc,2026 Ford Territory Hybrid First Impressions |...,2025-08-08T04:44:11Z,AutoDeal.com.ph,UCZZhHUkSSMSO-MAM_eCo_Tw,195209,1718,263,632000,172279696,https://www.youtube.com/watch?v=1jR49TNiKxc
13,bwxrVaJZXR8,Which climbs better? The 2026 Subaru Forester ...,2025-10-14T13:56:53Z,Driving Sports TV,UC4x0_RNxoNkfM8WtRWPoxWw,325326,4280,322,447000,175031732,https://www.youtube.com/watch?v=bwxrVaJZXR8
14,Z8PQ7LMjqNc,Ford Everest 2026 Review silver,2025-08-08T05:54:04Z,AutoShow TV,UCVJdpj3jzdyq7QweTcUK9rg,323222,4489,34,458000,290931312,https://www.youtube.com/watch?v=Z8PQ7LMjqNc
15,MC88KTCpF04,Novo GWM Haval H6 2026: O que mudou no SUV híb...,2025-11-17T20:00:29Z,Opinião Sincera,UCc0cU92Tf7rvd2gr-CpVO4Q,165833,6866,283,2150000,614129208,https://www.youtube.com/watch?v=MC88KTCpF04
16,OtVOpcg2bkE,No compraría una Ford Territory Hibrida!,2025-12-27T19:00:23Z,Lucas Abriata,UCOypnH-5DDOh1WXHJxm_t1A,165249,8302,593,369000,55738085,https://www.youtube.com/watch?v=OtVOpcg2bkE
17,Dllgtn_SHwk,ECOSPORT DA NOVA GERÇÃO - O SUV MAIS BARATO DA...,2025-10-22T20:58:14Z,Carro Chefe,UCMk1wBIsHmalYeE16GkD6bg,157336,12657,503,1680000,537071690,https://www.youtube.com/watch?v=Dllgtn_SHwk
18,RSBBo8pX-Kw,Ford Territory Hybrid Titanium X vs. BYD Seali...,2025-10-08T11:59:42Z,Top Gear Philippines,UCyXtvMat-saTbwDOY_yUw8w,153111,916,172,151000,51212219,https://www.youtube.com/watch?v=RSBBo8pX-Kw
19,J4OQCaOpQgA,Mazda CX 90 AWD 2026 Review,2025-07-14T12:06:53Z,AutoShow TV,UCVJdpj3jzdyq7QweTcUK9rg,308838,2878,32,458000,290931312,https://www.youtube.com/watch?v=J4OQCaOpQgA

In [ ]:
from youtube_transcript_api import YouTubeTranscriptApi

def extrair_transcricao(video_id):
    """
    Busca a transcrição do vídeo mantendo a estrutura de objetos da API.
    Retorna o texto em um bloco único para uso em LLMs.
    """
    # 1. Cria a instância da API exatamente como no seu código
    youtube_api = YouTubeTranscriptApi()

    try:
        # 2. Lista as transcrições disponíveis usando o método da instância
        transcript_list = youtube_api.list(video_id)
        
        # 3. Encontra a transcrição (preferencialmente em português ou inglês)
        transcript = transcript_list.find_transcript(['pt', 'en'])
        
        # 4. Busca os dados
        texto_dados = transcript.fetch()
        
        # 5. Processa o resultado para gerar um texto contínuo
        textos_limpos = []
        for item in texto_dados:
            # Mantendo a sua verificação de dicionário vs objeto
            texto = item.get('text') if isinstance(item, dict) else item.text
            
            # Limpa quebras de linha e espaços extras do texto e guarda na lista
            if texto:
                textos_limpos.append(texto.replace('\n', ' ').strip())
        
        # Retorna o texto completo unido por espaços
        texto_completo = " ".join(textos_limpos)
        return texto_completo

    except Exception as e:
        # Avisa sobre o erro de forma silenciosa para não quebrar o pipeline
        print(f"  [Aviso] Transcrição indisponível para o vídeo {video_id}: {e}")
        return None

def limpar_texto_para_llm(texto):
    """
    Limpa o texto removendo ruídos para otimizar o consumo de tokens 
    e melhorar o entendimento do LLM.
    """
    if not isinstance(texto, str) or not texto.strip():
        return ""
    
    # 1. Remove URLs e Links (O LLM não consegue clicar, só gastaria tokens)
    texto = re.sub(r'http\S+|www\.\S+', '', texto)
    
    # 2. Remove tags HTML residuais (muito comum em comentários do YouTube)
    texto = re.sub(r'<.*?>', '', texto)
    
    # 3. Substitui quebras de linha (\n), tabulações (\t) e múltiplos espaços por um único espaço
    texto = re.sub(r'\s+', ' ', texto)
    
    # 4. Remove repetições exageradas de pontuação (ex: "carro ruim!!!!!" vira "carro ruim!")
    # Isso evita que o modelo dê peso excessivo a um grito em vez do contexto
    texto = re.sub(r'([.!?])\1+', r'\1', texto)
    
    # 5. Remove aspas duplas/simples irregulares que podem quebrar a formatação JSON na saída do LLM
    texto = texto.replace('"', "'").replace('`', "'")
    
    # 6. Limpa espaços no início e no fim
    return texto.strip()

# --- Testando a função ---
if __name__ == "__main__":
    vid = 'BmYsInLDmrI'
    resultado = extrair_transcricao(vid)
    
    if resultado:
        print(f"Transcrição extraída com sucesso! ({len(resultado)} caracteres)")
        print(f"Trecho: {resultado[:200]}...")

        print(resultado)

Transcrição extraída com sucesso! (17405 caracteres)
Trecho: Esse é o novo Ford Territory 2025. Mudou tudo, agora anda de verdade. É um dos maiores espaços internos da categoria. Mas será que tem preço e condições para bater de frente com os outros chineses? Nã...
Esse é o novo Ford Territory 2025. Mudou tudo, agora anda de verdade. É um dos maiores espaços internos da categoria. Mas será que tem preço e condições para bater de frente com os outros chineses? Não, você não me escutou errado, não. Esse, apesar de ter o emblema da Ford, vem da China. O SUV de entrada agora da Ford no Brasil, mas que não é feito pela Ford. E além disso, vale a pena dizer que esse carro lá fora já ganhou o facelift e virou híbrido. Aqui também vai ser igual no vídeo de hoje a gente vai ver tudo sobre essa máquina aqui. Vamos falar da motorização, vamos falar do câmbio do espaço interno que ele dá um banho nos outros da categoria do porta presuntos. E é claro que a gente vai levar essa máquina, dar um rolê e ver qual é que é. E é claro que não tem lugar melhor pra gente começar a falar do Forge Territory, do que aqui a parte da frente também que eu escrito pelas pessoas mais legais do mundo, como a frenteira, bem bonito, né? Azulzinho também é covardia. Eu adoro o carro azul. Bem bonito, bem bonito. Conjunto ótico aqui, tudo LED, bem legal, bem bacana, mas que interessa pra gente aqui motorização. E abrindo aqui então temos acesso ao coração da fera. Manta acústica de belíssima qualidade, braços pantográficos. Aí sim, eu gostei. Motor é 1.5 turbo com injeção direta, porém só a gasolina é importado, né? Fazer o quê? E é corrente, tá? Corrente de comando. Não é correia dentada, muito menos banhada a óleo. São 169 ui cavalos e 25,4 de torque a 1500 giros. O que rola que eu sou um carro bem pesado, 1705 kg, 10 a mais sua sogra depois da feijoada, garantindo uma relação peso, potência de 10 kg para cada cavalinho. Tudo isso com câmbio automatizado de dupla embreagem, porém banhado a óleo de sete velocidades. Não, não é o power shift, fica tranquilo. Velocidade máxima de 180 km/h e 0 a 100 de 10 segundos. É isso. É um motor OK, porém um carro é pesado e é um motor que é só usado nele, o que talvez daqui um tempo manutenção, né? Enfim. E finalmente chegamos aqui na belíssima traseira do Ford Zoris. Somos brasileiros, gostamos de traseira assim bem bonita, né? O conjunto ótico, tudo LED aqui também. O que eu não gosto que a tampa termina muito rente aqui, né, do para-choque. Vai entender. Para abrir aqui, você pode abrir na chave ou só apertar aqui o botãozinho que o porta-mala se abre para você. E temos aqui acesso ao belíssimo porta-mala. São 440 L, todo forradinha. Quando você tira e coloca a mala, é forrado também. Lembrando, né, que SUV mede-se só até aqui. Então, tecnicamente você tem mais espaço. Mas se você precisar de mais espaço ainda, você pode dobrar os bancos aí só para 100. L. Dá para você levar uns 14 presuntos. que eles vão no conforto. Temos suspensão independente e vão livre do solo de 18 cm. A hora que você vai ver o step, é bicicletinha diferente das belíssimas rodas de liga leve aqui com freio a disco nas quatro rodas. Preço oficial R$ 215.000as. Tem culpa? Eu não, mas se você procurar aí, por exemplo, na Web Motors, um abraço para meus amigos da Web Motors, você acha modelos aí sendo zero km, obviamente sendo vendidos com descontinho de 10.000, 205.000. É isso, Lucão. Por essa grana já dá para pegar um híbrido plugin, só que chinês. Vamos ver se tem um alarme aqui. Tem, tem um alarme, só que é chinês. Um híbrido plugin. Não, um híbrido. É. E aí que tá o lance. Vamos, filho. Vai fechar não. Agora foi. E aqui tá o lance. Esse aqui também é. Finalmente se assustou. Entramos aqui no banco de trás do Ford Territory. Temos encostinto de três pontos, todos os airbags, o que é muito bom. E, cara, um banco muito confortável. Olha o espaço desse carro, velho. Ó, espaço pra cabeça aqui gigante. A gente tem um belíssimo tetão solar. Aqui temos temos redinha. Em breve você saberá o sapq para todos. Luizinha e o banco é bem inclinado, sabe? Ele é bem confortável mesmo. Abrindo aqui dois porta-copos, tal, tudo isso daí. Gostei da combinação desse banquito. Agora o que é aqui legal é você, ó, deixou um tap aí no like pr ajudar o canal. Você ajuda muito o canal. Seu tapinha no like. Bate, bate gostoso aí no like. Você me ajuda muito. O teto tá bem azulado, bem bonitão, né? Antes de falar do magnifico, aqui, vamos falar do acabamento aqui que é soft touch. Olha que loucura. Um toque para descer, abre inteiro e um toque para subir também. Tudo muito bem forrado. Ó, couro aqui também. Só vai ser plástico essa parte, que aqui uma imitação de madeira. Tem até textura de madeira. Uma luzinha para não ver um louco de tuingo arrancar sua porta. Borracha dupla. Olha o gatinho. Miau. Miau. Ele preferiu se retirar. Tá aí, ó. Realmente um carro muito bonito. Isso, isso tem que ser dito muito bem acabado e muito espaçoso. Eu não sou da NASA, mas eu vou mostrar o espaço agora pr vocês. Que piada horrível. Que piada horrível. Já segue nós lá no Instagram? Segue nós lá. Digita lá assim, ó. Prof Lucas Souza, até esqueci qual que era. Digita lá que você me acha lá. Postei vídeo primeiro desse carro lá. O conteúdo assim, ó. Uma droga. Uma droga. Legal que a gente tem luzinha aqui também. Vamos falar do espaço. Ó, esse banco tá regulado para mim cons muito bem. Tô 1,83 m. Aconteceu que é. Tá aqui a luzinha bem legal. Você consegue mudar lá na central multimídia? Ó o espaço, ó. Ó. Não, assim, ó. CPAN é o maior espaço interno da categoria. Se não for um melhor, tá, tá assim entre os dois ou três melhores. Eu não, o espaço interno do carro é absurdo. Ó, não tem túnel central, então dá para três pessoas viajarem bem aqui. Duas saidas diário para quem tá aqui atrás. Só uma porte USB, tá? Os três adultos aqui que saiam no soco. Realmente, cara, é espaço de Ford Landalro aqui, olha. Não, o carro realmente é muito espaçoso. Esse banco aqui, ó, tá o máximo pra frente possível. Olha como ele é lá na frente. Já depois eu mostro. Olha o espaço aqui, ó, com o banco mais pra frente possível. Eu cruzo a perna, velho. Olha aqui. Não, realmente é um absurdo. O que é pr elogiar, nós elogia. O que é pr criticar, nós critica. Consumo 8 e5 na cidade, 12 na estrada, lembrando só na gasolina. Milagres não, não existem. Vamos lá pra frente. Vem. Finalmente aqui no banco da frenteira do Ford Teror. Cara, que acabamento. Ó, isso aqui eles podiam dar aula, hein? Ó, tudo soft touch. Tu não encosta a mão num plástico, tá? Não encosta. Aqui tem um um uma borrachinha aqui pr você deixar alguma coisa. A luzinha aqui também que dá para você mudar, vai até a porta. Porta-luvas aqui tem tamanho bom. Ficou devendo uma luzinha aqui, né? Mas tá aí, ó. Belíssimo acabamento, viu? E sim, se você reparou a música, foi um eg. Foi um est, sim. Eu gosto de ser pontora. O banco é bem confortável. Ajustes eletrônicos, tanto pro motorista quanto pro passageiro. Tem ajuste de lombar que é uma coisa que eu que tô tiozinho, gosto bastante. Volante, por sua vez, temos ajuste de altura e de profundidade. Famosa regulagem kid. Eu gosto de fazer seu kid, também gosto do furadinho em couro. Temos aqui assistente de permanência em faxa, piloto automático adaptativo do melhor tipo par e anda. Já vou mostrar para vocês funcionando a tecla mais confusa do mundo. Já mostro melhor para vocês. Farol alto, limpador automático, retrovisorcrômico, tudo azulzinho, tá vendo? Bonito, né? Cor aqui também, cor aqui também. Todos os vídeos automáticos, um toque. O retrovisor rebate eletronicamente, tem alerta de ponto cego, tem repetidor de seta, também tem o botãozinho aqui para abrir o porta-malas aqui. É realmente um carrinho bem completo. Central multimídia tem Android Auto e Apple CarPlay sem fio, porém, cara, é muito simples e muito confusa. Ó, vindo para cá, né, eu tenho acesso aqui as principais funções, né? Inclusive, vamos começar falando, por exemplo, ó. Tô aqui mexendo no no num bregen qualquer. Quero mexer no ar condicionado. Ele até tem aqui função alta e umas teclinhas táteis. Então, por exemplo, a hora que eu clico, ó, ele até sobe, aí ele sobe o menu, né? Que é uma coisa bem de carro chinês que eu odeio isso. Se já tem isso, né? Você já tem um botãozinho, não precisava subir o menu e aí realmente ã me atrapalha, né? Eu consigo ligar a ventilação do banco. Tem que ser por aqui, mas consigo ligar. Tem o que? A bunda não faz falta tanto pro motorista quanto para o passageiro. E ela é um pouquinho confusa, né? Você vê que, né? Eu quero mudar algumas coisas. Então, configurações da carroceria, luzes, vou ter que vir aqui, travas. E ela e ela não é assim tão rápida também. Mas o pior para mim é o seguinte. Se eu quiser mudar os modos de condução, eu tenho que estar aqui nessa tela. Por exemplo, se eu estou no Android Auto, eu não consigo. Por quê? Porque eu tem que tá aqui qualquer tela que desde que não seja Android Auto ou Apple CarPlay. E aí eu faço assim e aí eu mudo. Ó lá, modo esporte, modo serra ou colina, lembrando que tração sofre inteira e modo eco. Tá aí mexer a luminosidade tem que ser por aqui também. Enfim, agora se eu tiver, por exemplo, no Android Auto e Apple CarPlay quiser fazer isso, que pena para mim, porque, ó, não faz, não faz. Então, preciso voltar pra home. Ainda bem que a gente tem aqui alguns botõezinhos, inclusive botãozinho da home. Aí eu consigo voltar, né? Se eu já tiver aqui, tiver sei lá, aqui fonte da juventude, fizer assim, eu consigo, né? Aqui tem aqui alguns atalhozinhos, tal, tal. Tá aí, né? Mas é bem simplesinha mesmo. Mais simples ainda. O painel de instrumentos. Calma que eu já mostro aqui. Um carregador por indução. Faltou uma saidinha de ar para gelar ele. Tudo couro aqui. Ali embaixo, ó. Duas portinhas USB, uma C, uma normal. Tudo emborrachado, tudo bonitão mesmo, viu? O carro é muito bem acabado. Botãozinho de volume que eu gosto bastante. Botãozinho pro carro estacionar sozinho. Sim, ele estaciona para você, que é sempre muito útil. freio de mão eletrônico, função auto hold, stop, start e desligar o sensor de estacionamento. Hora que você coloca na ré, temos câmera 360º, muito útil, né? A gente tem essa essa rondana aqui, ó. Se eu abro a porta e o carro começa a andar, ela sozinho trava o carro e coloca no P, né, pr te evitar fazer alguma coisa. E tem a função L aqui de lucão. Lucão, função low, é claro, estou brincando. Dois porta-copos. Eu gosto bastante que eles ficam aqui escondidinhos, né? Você consegue apertar aqui o botão tal, tal, tal. A chave tá aqui, né? Nada demais. Travado, destravar, abriu o porta-mala, não tem função ligar a distância. Aqui um bauzinho que a hora que você abre, você tem acesso, consegue deslizar isso daqui, né? Ficou faltando ser refrigerado para você deixar sua grosélia gelando, não é mesmo? Já aqui em cima, espelhinho com luz, bem legal. Porta óculos para você me usar Riban. Nada. Optei o lugar errado. Nada de Juliete. Num carro desse. Teto solar, né? Você pode abrir aqui. Bem legal, bem bacana. Dá um rolê com a gatinha num dia de sol aqui com o vento batendo nos seus cabelos, bem bonitão. Ou então você fecha aqui. E sim, momento para donos de Biodício chorar no banho. Temos redinha. Redinha assim. Dono de Volver X30 também pode chorar no banho, tá? Tem redinha, tem redinha. Olha aí, ó. Er redinha azul também esse carro aqui para quem quem é colorado, hein? Não vai gostar. As luizinhas aqui também de LED. O cinto tem regulagem de altura. E vamos falar aqui vergonhoso painel de instrumentos. Por que, Loucão? Bom, vamos lá. Primeiro, velocímetro. Velocímetro digital, temperatura do líquido de refecimento, nível de combustível, conta giros, né? Eu consigo mudar o painel de instrumentos? Consigo, ó, se eu vi aqui e mudar os modos de condução, então, por exemplo, boto no modo esportivo, ó lá, ele vai mudar, vai ficar, vai, vai ficar um jeito que é pior, porque eu não vejo direito a rotação, né? Enfim, fica nesse jeito meio assim, né? Enfim, as informações do meio eu já vou mostrar para vocês. Modo normal, que é o que estávamos antes, modo eco, que é o modo normal de outra cor, serra colina, que volta pro modo esporte, não consigo entender porquê. E aqui o modo normal de novo. Beleza, Lucão. Só isso. Só isso. E aí é muito louco que se eu desligo o carro no modo esportivo, o painel tá no modo esportivo. Eu desligo o carro, a hora que eu ligo de novo, o painel continua no modo esportivo. Mas o carro não vai entender. Vai entender. Agora para mexer aqui no meio, que é a única parte que eu consigo mexer, é esse botão, que também é um botão de volume. E agora, Lucão? Bom, você primeiro aperta essa tecla, aí você vai ter uma mensagem no painel, configurações de controles ativo ou de volume ativo. Controle ativo. Aí eu consigo mudar as informações. É isso. Que loucura é essa, velho? Que loucura é que loucura. Ó, eu consigo pressionar o botão para resetar. É isso. Não, não tem mais muita coisa. É muito genérico esse painel de instrumentos, mano. Vai entender, né? Meu Deus do céu. De qualquer maneira, chega de falar. Vamos levar essa máquina, dar um rolê e ver qual é que é. E é isso aí, galera. Olha a gente a bordo do Teror. Olha só quem te viu, quem te vê, Territor, que foi grande peada aqui do canal na geração antiga, né? Por quê? Porque ele era muito manco, né? É, andava pouco, bebia muito, continua bebendo, mas agora tá bem melhor de andar, né? A suspensão chinesa é um pouco mais molenga, né? Não é tão molenga que nem outros carros chineses, como Song, por exemplo, que eu acho muito molenga, mas sim, é molenga, cara. Sinceramente, se você tivesse um painel de instrumentos, ã, vamos colocar assim, olha, um Lifan aqui funcionando, hein? Se você tivesse um painel de instrumentos menos pior, um da Ford, um comuninho, tipo do do Bronco antes do facelift e um p e e uma e uma central multimídia decente, você nem ia falar que esse carro é é chinês, ia falar francês. Olha só que absurdo. Piloto automático adaptativo, funciona bonitinho, freia, acelera tal. Assistente permanece fa ainda é ruinzinho, mas é isso. É um carro muito confortável, muito espaçoso, anda bem, corre, melhor dizendo, não é um carro pesado. Ó, o carro da frente saiu, só dá um totó no acelerador, ele segue viagem. Então ele funciona no anda e para, né, do trânsito, enfim, tá aí. É um mega carro. Não, não, não é, é isso. Eu acho que se ele fosse mais barato, né, ainda tem todo esse lance de que lá fora já trocou tal, né, pô, 200 pila. Já que é para comprar carro chinês, você pode pegar um tigo oito, né? Já que é, né? Ah, mas esse é um Ford, um chinês. Eu acho que esse carro tinha que ser mais barato, só isso, né? Nessa faixa de preço do preço oficial, 215 paus, você já pode pensar em pegar um H6 Rev, que já é híbrido, que é a mesma coisa que esse carro lá fora, já tá híbrido. Se vem ou não pro Brasil, não sei, né? Faz um ano que a Ford lançou esse carro aqui, um pouco mais de um ano. Acho que é muito cedo para mudar, mas se não muda também não fica competitivo. Aí, aí é uma faca de dois legumes, que nem diria os mamonas assassinas. Vamos, vamos pra estrada acelerar e ver como é que é. Bora lá. Bora lá então. Ja na estrada, Jaque não, Ford aqui na estrada. Territory, não é o territory. Chega, chega, chega, chega, chega. Então vamos lá. É assim, ele é uma mais um sub urbano. Ele não tem tanta potência assim por causa do peso, né? Você vê que a gente nem troca de marcha tem, o que realmente é uma pena. Ah, loucão, mas quem que vai trocar marcha esportivamente? Não é só esportivamente, porque, por exemplo, você vai passar no alargamento, tudo bem que ele tem um modo L que talvez, talvez deva segurar ali a primeira marcha, mas é bom, né? você segurar na primeira, enfim, ó, pisei, ele vai eventualmente, eventualmente ele chega lá. É, é isso. Assistente permanência em faixa, ó, ó. Ele até que me devolve. Não é um assistente assim que vai me manter centralizado. Você vê que ele vai, né? Vai, vai fazendo um pinball assim. Rapaz, eu vou me ferrar na volta. Mas é isso, ó que eu falei, a suspensão é um pouquinho mais molenguinha, né, como todo o carro chinês. Exceção o H6 GT, só o GT, tá? Os outros não, os outros são molenga. É isso, mano. Os outros Hás da vida. Enfim. E é um carro meio genérico, cara. Nessa faixa de preço da onde ele vem tem melhores. É isso. Veículo isso. É particularmente rápido, não é particularmente empolgante, é confortável para caramba. Belo espaço interno e belo acabamento. Mas nesse preço será? Controle de tração, estabilidade desligado. Módelo sport ar desligado. 8.8 segundos. Aí tá ruim. Não tá bom, mas também não tá ruim, né? 9 segundos, mais ou menos 8.8 e 9 segundos. É isso pro 1.5 turbo. Tá bom, tá OK. Só é isso. Não é rápido, mas também não é alerdão. E esse foi o novo Ford Terretor, o carro predileto da banda Sepultura, nota 7,5. Ele dá um show de acabamento de espaço interno. Esse carro poderia facilmente ser uns sete lugares, mas é uns cinco lugares com bastante espaço interno. É o motor. Vamos lá. Não é um carro super empolgante de dirigir mesmo, porque é um carro bem pesado, né? É. E tem todo o lance dele já estar sendo atualizado, já foi atualizado lá fora, né? que lá chama Equador, que talvez seja atualizado aqui, ou talvez não. Não sabemos, não sabemos. É, desempenho, não é o grande lance. O sistema ali multimídia também é bem genérico, chinês na minha humilde opinião, mas sim, é um carro bem bonito. Eu esperaria mais um pouco para ver como que vai ser essa situação, se vai atualizar aqui no Brasil ou não. Toantos vídeos aqui no canal para você ass. Nos vemos na próxima aí. Valeu.

In [ ]:
import os
from googleapiclient.discovery import build
from dotenv import load_dotenv

# Reutilizando a função de limpeza definida anteriormente
import re

def limpar_texto_para_llm(texto):
    if not isinstance(texto, str) or not texto.strip(): return ""
    texto = re.sub(r'http\S+|www\.\S+', '', texto)
    texto = re.sub(r'<.*?>', '', texto)
    texto = re.sub(r'\s+', ' ', texto)
    texto = re.sub(r'([.!?])\1+', r'\1', texto)
    return texto.replace('"', "'").strip()

def coletar_comentarios(video_id, max_resultados=200):
    """
    Coleta comentários de um vídeo usando paginação.
    Retorna uma lista de dicionários com autor, texto limpo e métricas.
    """
    load_dotenv()
    youtube = build('youtube', 'v3', developerKey=os.getenv('YOUTUBE_API_KEY'))
    
    comentarios_totais = []
    next_page_token = None
    
    try:
        while len(comentarios_totais) < max_resultados:
            # Executa a requisição
            response = youtube.commentThreads().list(
                part='snippet',
                videoId=video_id,
                maxResults=min(100, max_resultados - len(comentarios_totais)),
                textFormat='plainText',
                order='relevance',
                pageToken=next_page_token
            ).execute()
            
            for item in response.get('items', []):
                snippet = item['snippet']['topLevelComment']['snippet']
                
                texto_bruto = snippet['textDisplay']
                texto_limpo = limpar_texto_para_llm(texto_bruto)
                
                # Só adicionamos se o comentário não ficou vazio após a limpeza
                if texto_limpo:
                    comentarios_totais.append({
                        'texto': texto_limpo,
                        'likes': snippet['likeCount'],
                        'total_respostas': item['snippet']['totalReplyCount'],
                        'data': snippet['publishedAt']
                    })
            
            # Verifica se existe uma próxima página
            next_page_token = response.get('nextPageToken')
            if not next_page_token:
                break
                
        print(f"  [Sucesso] {len(comentarios_totais)} comentários coletados para o vídeo {video_id}")
        return comentarios_totais

    except Exception as e:
        print(f"  [Erro] Falha ao coletar comentários do vídeo {video_id}: {e}")
        return []

# --- Exemplo de Uso ---
if __name__ == "__main__":
    v_id = 'BmYsInLDmrI'
    lista_comentarios = coletar_comentarios(v_id, max_resultados=50)

  [Sucesso] 50 comentários coletados para o vídeo BmYsInLDmrI
[@PauloSergio-tz7sj]: Só lembro da piada 'mais rápido que o Ford territory 'kkkkkkk... (Likes: 131)
[@Marquiiiz]: Estou com ele a 6 meses, tem sido a melhor escolha pra mim, carrro super confortavel, ate aqui nenhu... (Likes: 93)
[@nicolasborges2022]: Inacreditável o acabamento, o conforto e o espaço deste carro! 👏🏻 Muito bem completo e com vários it... (Likes: 44)

In [46]:
import os
import re
import time
import pandas as pd
from dotenv import load_dotenv
from googleapiclient.discovery import build
from youtube_transcript_api import YouTubeTranscriptApi
# ==========================================
# 3. EXECUÇÃO DO PIPELINE
# ==========================================
if __name__ == "__main__":
    load_dotenv()
    
    # Simulando a carga da sua base de dados (Poderia ser pd.read_csv('seus_videos.csv'))

    df_videos = pd.read_csv('base_ford_territory.csv', delimiter=';')
    
    linhas_transcricao = []
    linhas_comentarios = []
    
    print("Iniciando processamento dos vídeos...\n")
    
    for index, row in df_videos.iterrows():
        vid_id = row['video_id']
        canal = row['canal_nome']
        titulo = row['titulo']
        
        print(f"Processando [{index+1}/{len(df_videos)}]: {titulo[:40]}...")
        
        # --- ETAPA A: TRANSCRIÇÃO ---
        print("  -> Baixando transcrição...")
        texto_transcricao = extrair_transcricao(vid_id)
        
        linhas_transcricao.append({
            'video_id': vid_id,
            'canal_nome': canal,
            'titulo_video': titulo,
            'texto_transcricao': texto_transcricao,
            'llm_categoria_veiculo': None,
            'llm_pontos_positivos': None,
            'llm_pontos_negativos': None,
            'llm_nota_geral': None
        })
        
        # --- ETAPA B: COMENTÁRIOS ---
        print("  -> Coletando comentários do público...")
        comentarios_extraidos = coletar_comentarios(vid_id, max_resultados=50) # Limitado a 50 para teste rápido
        
        for c in comentarios_extraidos:
            linhas_comentarios.append({
                'video_id': vid_id,
                'canal_nome': canal,
                'texto_comentario': c['texto'],
                'likes_comentario': c['likes'],
                'data_comentario': c['data'],
                'llm_sentimento': None,
                'llm_tema_principal': None
            })
            
        # Pequena pausa para evitar bloqueios por taxa de requisição (Rate Limit)
        time.sleep(1)

    # ==========================================
    # 4. SALVANDO OS DADOS PROCESSADOS
    # ==========================================
    df_transcricoes = pd.DataFrame(linhas_transcricao)
    df_comentarios = pd.DataFrame(linhas_comentarios)
    
    # Salvando em CSV
    df_transcricoes.to_csv('pipeline_transcricoes_real.csv', index=False, sep=';', encoding='utf-8')
    df_comentarios.to_csv('pipeline_comentarios_real.csv', index=False, sep=';', encoding='utf-8')
    
    print("\n✅ Processamento concluído com sucesso!")
    print(f"Total de Transcrições processadas: {len(df_transcricoes)}")
    print(f"Total de Comentários coletados: {len(df_comentarios)}")
    print("Arquivos salvos: 'pipeline_transcricoes_real.csv' e 'pipeline_comentarios_real.csv'")

Iniciando processamento dos vídeos...

Processando [1/20]: A REVIRAVOLTA DA RENAULT! ATROPELOU COMP...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo BkFNJYONHTM
Processando [2/20]: New CHERY Tiggo 8 2026! Review...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo w9p5i5NP0fA:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=w9p5i5NP0fA! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo w9p5i5NP0fA
Processando [3/20]: FORD TERRITORY 2025 (Titanium) - Test - ...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo UQm_Awc4sLU:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=UQm_Awc4sLU! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['pt', 'en']

For this video (UQm_Awc4sLU) transcripts are available in the following languages:

(MANUALLY CREATED)
None

(GENERATED)
 - es ("Spanish (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - en ("English")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo UQm_Awc4sLU
Processando [4/20]: La Ford Territory Es Distinta...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo GDNc13R1YA4:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=GDNc13R1YA4! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['pt', 'en']

For this video (GDNc13R1YA4) transcripts are available in the following languages:

(MANUALLY CREATED)
None

(GENERATED)
 - es ("Spanish (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - en ("English")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo GDNc13R1YA4
Processando [5/20]: 2026 Ford Territory Review UAE | Ford Te...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 18 comentários coletados para o vídeo QDLRS1hiMcE
Processando [6/20]: Jetour T2 Review - The Best Value Advent...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo 9v9iSnikNOw
Processando [7/20]: Novo Renault BOREAL: Melhor SUV do Brasi...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo 0CzJO5FVnDE
Processando [8/20]: Jetour T1 2026 Review...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo y4_h7C-SBeY:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=y4_h7C-SBeY! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 19 comentários coletados para o vídeo y4_h7C-SBeY
Processando [9/20]: Jetour T1 2026 Review Black Edition...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo MgFEBIYEO5I:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=MgFEBIYEO5I! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 20 comentários coletados para o vídeo MgFEBIYEO5I
Processando [10/20]: New CHERY Tiggo 9 2026! Review...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo K5lvKm1H7kM:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=K5lvKm1H7kM! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 14 comentários coletados para o vídeo K5lvKm1H7kM
Processando [11/20]: Jetour Dashing ECO 2026 Review...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo XRYeckv9zk8:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=XRYeckv9zk8! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 27 comentários coletados para o vídeo XRYeckv9zk8
Processando [12/20]: TIGGO 8 PRO 2026 NOVO PREÇO! #cherrytigo...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo EXvSxIgahs4
Processando [13/20]: 2026 Ford Territory Hybrid First Impress...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo 1jR49TNiKxc
Processando [14/20]: Which climbs better? The 2026 Subaru For...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo bwxrVaJZXR8
Processando [15/20]: Ford Everest 2026 Review silver...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo Z8PQ7LMjqNc:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=Z8PQ7LMjqNc! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['pt', 'en']

For this video (Z8PQ7LMjqNc) transcripts are available in the following languages:

(MANUALLY CREATED)
None

(GENERATED)
 - ru ("Russian (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - en ("English")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 32 comentários coletados para o vídeo Z8PQ7LMjqNc
Processando [16/20]: Novo GWM Haval H6 2026: O que mudou no S...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo MC88KTCpF04
Processando [17/20]: No compraría una Ford Territory Hibrida!...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo OtVOpcg2bkE:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=OtVOpcg2bkE! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['pt', 'en']

For this video (OtVOpcg2bkE) transcripts are available in the following languages:

(MANUALLY CREATED)
None

(GENERATED)
 - es ("Spanish (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - en ("English")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo OtVOpcg2bkE
Processando [18/20]: ECOSPORT DA NOVA GERÇÃO - O SUV MAIS BAR...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo Dllgtn_SHwk
Processando [19/20]: Ford Territory Hybrid Titanium X vs. BYD...
  -> Baixando transcrição...
  -> Coletando comentários do público...
  [Sucesso] 50 comentários coletados para o vídeo RSBBo8pX-Kw
Processando [20/20]: Mazda CX 90 AWD 2026 Review...
  -> Baixando transcrição...
  [Aviso] Transcrição indisponível para o vídeo J4OQCaOpQgA:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=J4OQCaOpQgA! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
  -> Coletando comentários do público...
  [Sucesso] 25 comentários coletados para o vídeo J4OQCaOpQgA

✅ Processamento concluído com sucesso!
Total de Transcrições processadas: 20
Total de Comentários coletados: 805
Arquivos salvos: 'pipeline_transcricoes_real.csv' e 'pipeline_comentarios_real.csv'

In [47]:
df_comentarios = pd.read_csv('pipeline_comentarios_real.csv', delimiter=';')
df_comentarios

,video_id,canal_nome,texto_comentario,likes_comentario,data_comentario,llm_sentimento,llm_tema_principal
0,BkFNJYONHTM,Carro Chefe,Cadê o tapa no like? 😂,613,2025-11-06T19:02:46Z,NaN,NaN
1,BkFNJYONHTM,Carro Chefe,"Salve Lucão, sou um dos analistas de engenhari...",2713,2025-11-06T21:56:35Z,NaN,NaN
2,BkFNJYONHTM,Carro Chefe,27kg de torque Corrente de comando 4 cilindros...,813,2025-11-07T17:30:08Z,NaN,NaN
3,BkFNJYONHTM,Carro Chefe,"por essa ninguém esperava, finalmente uma mont...",401,2025-11-06T21:24:03Z,NaN,NaN
4,BkFNJYONHTM,Carro Chefe,Ficou bonito. E o acabamento faz o taos chorar...,572,2025-11-06T19:59:30Z,NaN,NaN
...,...,...,...,...,...,...,...
800,J4OQCaOpQgA,AutoShow TV,ai,0,2026-04-16T07:15:29Z,NaN,NaN
801,J4OQCaOpQgA,AutoShow TV,CarPlay doesn’t work while driving,0,2026-04-02T17:26:21Z,NaN,NaN
802,J4OQCaOpQgA,AutoShow TV,I love mine. Glad I got rid of my Tesla,0,2026-01-04T00:57:54Z,NaN,NaN
803,J4OQCaOpQgA,AutoShow TV,గోడి బాయ్ ok,2,2025-07-14T12:12:02Z,NaN,NaN
804,J4OQCaOpQgA,AutoShow TV,BMW 😂,0,2025-11-29T06:56:08Z,NaN,NaN

In [48]:
df_transcricoes = pd.read_csv('pipeline_transcricoes_real.csv', delimiter=';')
df_transcricoes

,video_id,canal_nome,titulo_video,texto_transcricao,llm_categoria_veiculo,llm_pontos_positivos,llm_pontos_negativos,llm_nota_geral
0,BkFNJYONHTM,Carro Chefe,A REVIRAVOLTA DA RENAULT! ATROPELOU COMPASS E ...,Esse é o novo Renault Boreal e é o melhor carr...,NaN,NaN,NaN,NaN
1,w9p5i5NP0fA,NewCar TV,New CHERY Tiggo 8 2026! Review,NaN,NaN,NaN,NaN,NaN
2,UQm_Awc4sLU,MatiasAntico,FORD TERRITORY 2025 (Titanium) - Test - Matías...,NaN,NaN,NaN,NaN,NaN
3,GDNc13R1YA4,Lucas Abriata,La Ford Territory Es Distinta,NaN,NaN,NaN,NaN,NaN
4,QDLRS1hiMcE,OTO Drive,2026 Ford Territory Review UAE | Ford Territor...,today. We have the Ford territory with us. Now...,NaN,NaN,NaN,NaN
5,9v9iSnikNOw,Cars.co.za,Jetour T2 Review - The Best Value Adventure SU...,[music] [music] Hello and welcome back to the ...,NaN,NaN,NaN,NaN
6,0CzJO5FVnDE,Opinião Sincera,Novo Renault BOREAL: Melhor SUV do Brasil? Det...,"Este é o novíssimo Renault Boreal, USV grande,...",NaN,NaN,NaN,NaN
7,y4_h7C-SBeY,AutoShow TV,Jetour T1 2026 Review,NaN,NaN,NaN,NaN,NaN
8,MgFEBIYEO5I,AutoShow TV,Jetour T1 2026 Review Black Edition,NaN,NaN,NaN,NaN,NaN
9,K5lvKm1H7kM,NewCar TV,New CHERY Tiggo 9 2026! Review,NaN,NaN,NaN,NaN,NaN
10,XRYeckv9zk8,AutoShow TV,Jetour Dashing ECO 2026 Review,NaN,NaN,NaN,NaN,NaN
11,EXvSxIgahs4,MyCars,TIGGO 8 PRO 2026 NOVO PREÇO! #cherrytigo8 #tig...,As vendas do Tigo 8 Pro 2026 dispararam e ele ...,NaN,NaN,NaN,NaN
12,1jR49TNiKxc,AutoDeal.com.ph,2026 Ford Territory Hybrid First Impressions |...,"[Music] Not too long ago, we had a very fun in...",NaN,NaN,NaN,NaN
13,bwxrVaJZXR8,Driving Sports TV,Which climbs better? The 2026 Subaru Forester ...,Which one has the better all-wheel drive syste...,NaN,NaN,NaN,NaN
14,Z8PQ7LMjqNc,AutoShow TV,Ford Everest 2026 Review silver,NaN,NaN,NaN,NaN,NaN
15,MC88KTCpF04,Opinião Sincera,Novo GWM Haval H6 2026: O que mudou no SUV híb...,"É, meus amigos, vocês não estão vendo errado, ...",NaN,NaN,NaN,NaN
16,OtVOpcg2bkE,Lucas Abriata,No compraría una Ford Territory Hibrida!,NaN,NaN,NaN,NaN,NaN
17,Dllgtn_SHwk,Carro Chefe,ECOSPORT DA NOVA GERÇÃO - O SUV MAIS BARATO DA...,Esse é o novo Ford Territory 2026. E ao contrá...,NaN,NaN,NaN,NaN
18,RSBBo8pX-Kw,Top Gear Philippines,Ford Territory Hybrid Titanium X vs. BYD Seali...,Hybrid crossovers are everywhere regardless of...,NaN,NaN,NaN,NaN
19,J4OQCaOpQgA,AutoShow TV,Mazda CX 90 AWD 2026 Review,NaN,NaN,NaN,NaN,NaN